### ISSUE TITLE
How quickly is the site updating when track changes are merged?

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-feedback#10]
Should updates to tracks be "quick" or is that something still coming?  As a test I updated my BIO in maintainers.json, I was curious to see how quickly my change would hit the site.  So far the change has not appeared on the site, been roughly 10 minutes....

**Comment by NobbZ** [comment]
README says every 5 minutes…

https://github.com/exercism/v2-feedback#improved-deploys
> ## Improved deploys
>
> The old site has a truly horrendous deploy cycle, the result of which is that changes to language tracks can take a day (or several) to make it to the site. In the prototype, changes to track repositories get updated on the site every 5 minutes.

**Comment by rpottsoh** [comment]
Thanks @NobbZ, I just wasn't sure if we should expect it to be working at this point.  Or more precisely what is being covered every 5 minutes.  Anyway, it is taking longer than I expected so I thought it wise to raise the issue, better to be safe.

**Comment by kytrinyx** [comment]
It is currently every 5 minutes, unless it's broken. Or unless we have forgotten to add logic to bust the caches.

Thanks for raising this, @rpottsoh.

**Comment by rpottsoh** [comment]
I am noticing today that the site is updating quite quickly.  I am going to close this issue.
