### ISSUE TITLE
Breadcrumb path is inconsistent

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#100]
If I view a [specific solution](https://v2.exercism.io/tracks/csharp/exercises/etl/solutions/723c6fe0cd3158dec06849bc), the crumb path is: Language Tracks -> C# Track -> Community Solutions -> This Solution

This makes sense, as the crumb path represents the hierarchy for the solution. However, if I click on the [Community Solutions link](https://v2.exercism.io/tracks/csharp/exercises/etl/solutions), the crumb path changes to: Language Tracks -> C# Track -> Your Solution to Etl -> Community Solutions

I think this should be: Language Tracks -> C# Track -> Community Solutions -> Your Solution to Etl

**Comment by kytrinyx** [comment]
Agreed—that would make more sense. @iHiD might actually have something else in mind here that he hasn't implemented yet, but either way we should definitely have a hierarchy that makes sense.

**Comment by iHiD** [comment]
> @iHiD might actually have something else in mind here that he hasn't implemented yet

So yes :) This actually worked well before we did ETL.

1) In v2, you should only see links to solutions on things you've done. At that point, the URL is always "Your solution to ETL -> Community Solutions". 
2) However, for SEO, Google can crawl all solutions which is the "Language Tracks -> C# Track -> Community Solutions -> This Solution" version.

So when you were logged in you would never see (2). However, now you're able to see:
a) solutions you've liked to exercises you haven't completed
b) solutions on others' profiles to exercises you haven't completed

I deliberately don't want to expose the  "Language Tracks -> C# Track -> Community Solutions" URL when you're logged in, else you can get back to view solutions to all exercises, so I need to think about how this should work. I'll book some product-team discussion time in :)

**Comment by iHiD** [comment]
Triaged to exercism/reboot#133.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
