### ISSUE TITLE
I'm off for a few days

### ISSUE THREAD

**Issue by iHiD** [exercism/v2-feedback#103]
Hi everyone. 

I just wanted to say I'm having the rest of this week without tech (starting from now), then MC'ing Full Stack Fest in Barcelona (pls come say hello if you're there!) next week. That means I won't be triaging or responding to issues until ~11th Sept. 

Please continue to post anything you find (your feedback has been incredible and we're massively grateful for all the testing - thank you) and I'll get back to fixing everything when I'm back, and then hopefully we can get this launched for real in September! :)

Thanks!
iHiD

**Comment by Insti** [comment]
Have a good break :wave:

**Comment by rpottsoh** [comment]
@iHiD since you wont see this till you get back.

Welcome back!  I hope you had an enjoyable time in Spain.

**Comment by iHiD** [comment]
I'm back! :) Thank you both 💙
