### ISSUE TITLE
Coder drawing appear to have no hands

### ISSUE THREAD

**Issue by budmc29** [exercism/v2-feedback#104]
To my eye it looks like he has no hands.
It is more obvious in the values page https://v2.exercism.io/values.

![1-82f2f2924d599ab5e09a13e82f3a95fa7c82424d9ec0bded352540d4563e636b](https://user-images.githubusercontent.com/7063792/29897387-91c55be4-8dd8-11e7-8908-ed648c499be8.png)

**Comment by NobbZ** [comment]
For me it looks as if his hands are covered by the laptops lid and he is actually coding…

**Comment by ErikSchierboom** [comment]
I think it is because you don't see a gap between his arms and his torso. This example does have that and I must admit it makes it easier to see the person is typing:

![image](https://user-images.githubusercontent.com/135246/29994139-b5f283b0-8fc8-11e7-856d-31398461c737.png)

**Comment by budmc29** [comment]
I don't mind the issue being closed, like I said in the description "To **my eye**".
I know he's typing, but on the https://v2.exercism.io/values page the image is much smaller and it's looked incredibly weird.

This can be easily fixed by having a small gap or adding shadows, or the issue can just be closed.

**Comment by Insti** [comment]
Encouraging coders with no arms/hands would fit with the "coding is for everyone" inclusiveness goals of nextercism...

**Comment by iHiD** [comment]
@nicolechalmers Your call on this one.

**Comment by iHiD** [comment]
@budmc29 FYI we've fixed this but I'm not sure we've deployed it yet :)

**Comment by iHiD** [comment]
Commit here: https://github.com/exercism/prototype/commit/76ee6b50300f0e40574fe841bd9a6b66c3f804ab
