### ISSUE TITLE
Markdown parsing with red-carpet has some issues

### ISSUE THREAD

**Issue by Stargator** [exercism/v2-feedback#105]
As discovered in https://github.com/exercism/dart/issues/22, red-carpet has a habit of breaking the numbering order for numbered lists. As an example:

![redcarpet01](https://user-images.githubusercontent.com/7527155/29997643-4c67b906-8fe6-11e7-99db-b129c4ea6751.png)

As I looked into the issue and tried to find some workaround, these are my findings:

Redcarpet with code formatting as seen in the image above does not convert to the expected html format. The code formatting breaks the numbering for lists.

I created a jekyll project to test the Markdown library redcarpet. You can find it [a project for redcarpet here](https://github.com/Stargator/markdown-with-redcarpet/tree/red-quotes) and [a jekyll project using kramdown here](https://github.com/Stargator/markdown-with-kramdown).

The problem remains when using quotes with redcarpet:
![redcarpet-quotes](https://user-images.githubusercontent.com/7527155/29997577-bf8820d0-8fe4-11e7-975c-a43dc1cc3543.png)

Or **not** using any formatting at all:
![red-no-formatting](https://user-images.githubusercontent.com/7527155/29997600-39cb0b78-8fe5-11e7-92ed-adcdd645e779.png)

Comparatively, Kramdown does *not* have this issue:
![kramdown-mark](https://user-images.githubusercontent.com/7527155/29997603-55df4612-8fe5-11e7-899f-277bb1837f2a.png)

Though I do not know the full scope of our use of redcarpet, so I do not know if there is anything specific that redcarpet does that we depend on.

**Comment by Stargator** [comment]
@iHiD @kytrinyx 

[According to the Markdown syntax](https://daringfireball.net/projects/markdown/syntax#list), code blocks need to be double spaced. Kramdown is more forgiving in this case. But I have a solution and will create a pull request for java as well as look for any instances of this case in v1.

But as far as v2, I do not know where, if any, this issue may need to be addressed.

You can view the working example in [this branch of a example repo](https://github.com/Stargator/markdown-with-redcarpet/tree/red-double-space). Run `bundle install` and `bundle exec jekyll serve`. Assuming you have Ruby, Jekyll, and Bundler installed.

Screenshot as proof. Notice how Windows, which in this case is double indented, renders properly and macOS, which remain untouched, does not:

![windows-vs-mac](https://user-images.githubusercontent.com/7527155/29997798-9bae5e9e-8fea-11e7-9cec-1b985a728189.png)

**Comment by kytrinyx** [comment]
Thank you @Stargator!

**Comment by Stargator** [comment]
I have identified, the Dart, Java, and Kotlin exercises as needing double indentations. I haven't seen it in the other non-exercise pages, but I may have missed something.

I have not checked the v2 pages and likely, will not have the time to do so. So I encourage anyone interested to undertake that part of this ticket.

**Comment by iHiD** [comment]
@stargator Is there any action here required for the website repo, or just for the track repos?

**Comment by Stargator** [comment]
It really is on any Markdown files that use the code blocks. They need to be double indented in order to ensure they are properly formatted by whatever markdown parser we use.

**Comment by Stargator** [comment]
Just following up, I know the kotlin track hasn't implemented the changes due to questions regarding the syntax.

**Comment by kytrinyx** [comment]
> Just following up, I know the kotlin track hasn't implemented the changes due to questions regarding the syntax.

@Stargator would you point me to those questions? I've lost track and would love to get this straightened out if possible.

**Comment by Stargator** [comment]
@kytrinyx https://github.com/exercism/kotlin/pull/107#issuecomment-327067839

**Comment by kytrinyx** [comment]
@Stargator I still don't understand.

Is the question whether or not the v2 site renders double-indented code blocks in lists correctly?

**Comment by Stargator** [comment]
The question is about still seeing some code block tags ``` in some of the rendered pages. See: https://github.com/Stargator/kotlin/blob/265ad54ba5ff92eca8c1f7f313212555bfcd3e8b/docs/TESTS.md

I thought I addressed it, but I admit I haven't looked at the document in awhile.

**Comment by kytrinyx** [comment]
You have inconsistent indentation.

If you indent with exactly four spaces, it will all work: https://github.com/kytrinyx/indentation/blob/master/TESTS.md

**Comment by iHiD** [comment]
@kytrinyx @Stargator
- Does this require action on the website?
- Does this require action in the track repos?
- Can this issue be closed?

Thanks.

**Comment by Stargator** [comment]
@iHiD I don't know. I'll have to look again at the pages for the tracks and see if any have the problem. Though I think all the ones I identified were fixed, they could have regressed. I'll have some time to look at it this week.

**Comment by iHiD** [comment]
I've closing this as we're about to move things around. Pls reopen in exercism/exercism.io if the issue remains :)
