### ISSUE TITLE
Delete uploaded files

### ISSUE THREAD

**Issue by budmc29** [exercism/v2-feedback#107]
I had a look through the issues and could not find any reference to this, or maybe I missed it.

Is there any way to delete a submission? By mistake I uploaded my npm_folder with the submission and I would like to delete the folder/files.

![no_file_deletion](https://user-images.githubusercontent.com/7063792/30040315-8aafdc70-91d5-11e7-8018-aeea8e6059ee.png)

**Comment by kytrinyx** [comment]
Thanks @budmc29 I don't think we have a way to delete submissions at the moment.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
