### ISSUE TITLE
Solution box height bug

### ISSUE THREAD

**Issue by budmc29** [exercism/v2-feedback#108]
Os: Ubuntu 14
Chromium 58

![1](https://user-images.githubusercontent.com/7063792/30040375-601f2d2a-91d6-11e7-9c4f-a9aff396526a.png)

I don't know what is the browser support for Exercism v2.
My guess is that it's only the latest browsers? I'll restrain myself from filing more design bugs until I get an answer for that.

**Comment by kytrinyx** [comment]
For the moment we've not done any fixing for different browsers. Here's the bit in the v2 readme/announcement that deals with this: https://github.com/exercism/v2-feedback/blob/master/README.md#browsers-and-devices

**Comment by budmc29** [comment]
Yes, thank you, I read that part. What's the browser support that you guys are focusing on, should I file any bugs in Chromium and an older version of Firefox, or for launch the focus will only be on modern browsers (read last versions)?

**Comment by iHiD** [comment]
Triaged to exercism/reboot#139

**Comment by iHiD** [comment]
@budmc29 Any browser in the last couple of years feels like the right target for me. If someone might sensibly still be on it, and it supports sensible standards, then that feels like we should target it. Beyond that, I've not got specifics :)

**Comment by budmc29** [comment]
Thanks for the clarification.

**Comment by iHiD** [comment]
This is fixed on master now, so I'm going to close it here. It will show up in the next beta (mid-June). Please let me know if you have any further scrolling issues then. Thanks! :)

For reference this is what it looks like now on my mac and what it should look like everywhere: http://recordit.co/5DNrBjbAzj
