### ISSUE TITLE
Turn on HTTPS

### ISSUE THREAD

**Issue by veganstraightedge** [exercism/v2-feedback#109]
If the site is hosted on Heroku, it's very easy and free to turn on HTTPS.

`heroku certs:auto:enable`

If it's hosted somewhere else…  `¯\_(ツ)_/¯ `

**Comment by kytrinyx** [comment]
Hey @veganstraightedge -- v2 is https already. v1... not so much. I tried, got the heroku cert thing working, but then got stuck on the fastly integration.

**Comment by iHiD** [comment]
I'm going to mark this as wontfix as it's not relevant to v2-feedback, and probably not worth worrying about for v1 as it will be deprecated soon. @veganstraightedge Thank you for reporting though - https is super important moving forward! :)
