### ISSUE TITLE
Downloading without joining first gives incorrect error message

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#11]
When someone tries to `nextercism d hello-world --track=$track` in a track he hasn't joined yet, he will get an error `Solution not found`.

We are neither asking for a solution, nor did we expect that there is anything. Instead we had expected the CLI to report something along the lines "exercise not unlocked yet or track not joined"

**Comment by Insti** [comment]
Same error message if you try to download a 'locked' problem.

**Comment by kytrinyx** [comment]
Thanks @NobbZ, @Insti — all of the error handling is going to need some serious attention. Having specific use cases like this is very helpful.
