### ISSUE TITLE
Multiple tracks inconveniences

### ISSUE THREAD

**Issue by budmc29** [exercism/v2-feedback#110]
I understand the focus will be for the new users, and I'm not really sure how many new programmers will try to work on many tracks at once (probably few or none), but here are some inconveniences:

1. No way to see the language description after joining the track, a user might want to do this after that when they joined multiple languages and try to learn more about one of them (happened to me with one language).
2. No way to exit from a track you joined (not having it joined anymore), this might seem like no one would want that, but what about people that want to have things neat and tidy, and would like to remove one or more tracks they are not interested in
3. There seem to be an inconsistency between same exercises order for different languages (I am referring to the ones available in both languages)  

    I know there are plans to have a base track for each language, but would there be any reason to have them in the same order when the same available exists?
 That would be beneficial when you want solve the same exercise in 2+ languages.
    <details>
    Crystal  
  
    Hello World, Hamming, (...), Bob, (...), Leap  

    Vim  
    Hello World, Leap, Hamming, Bob
  </details>

**Comment by kytrinyx** [comment]
Thank you @budmc29 -- we intend to make it easy to work on multiple tracks concurrently.

> No way to see the language description after joining the track

This has been reported, and we are thinking about how best to address it.

> No way to exit from a track you joined

This has been reported, and will be addressed.

> There seem to be an inconsistency between same exercises order for different languages

This is fine. We don't expect consistency between languages. The exercise might be very different in different languages, or even if they're similar, it could be much harder in some languages than others. And even if they are similarly difficult, then other exercises in the language might mean that it makes sense to place it in a different position.
