### ISSUE TITLE
reboot repository private?

### ISSUE THREAD

**Issue by Insti** [exercism/v2-feedback#112]
I've noticed @iHiD referencing the https://github.com/exercism/reboot repository, but that is inaccessible to me. 

Is it a private repository?
Is this intentional?
What are the plans/timescale for the source visibility of nextercism?

**Comment by Insti** [comment]
@rpottsoh [also noticed this](https://github.com/exercism/v2-feedback/issues/111#issuecomment-328561499)

[@iHiD replied](https://github.com/exercism/v2-feedback/issues/111#issuecomment-328565613)
> Yeah. It's private. It's where all the discussions about everything have been over the last 9 months, where we wanted just a core product team working on them (ie, Katrina and Thalamus team). We're now using it for tracking issues for website. We'll probably scrap it once we launch.

**Comment by kytrinyx** [comment]
> What are the plans/timescale for the source visibility of nextercism?

The source visibility of nextercism has been available since we launched the beta: https://github.com/exercism/prototype
