### ISSUE TITLE
Upcoming or planned tracks not listed

### ISSUE THREAD

**Issue by wolf99** [exercism/v2-feedback#114]
It's not possible to see upcoming or planned tracks. Maybe this is in the TODO work or something. 

I got started with Exercism on the C track, which still hasn't graduated from upcoming. If I came to the site wanting to do some C exercises and saw it wasn't listed I would leave again without even signing up, without knowing that there is in fact a C track, that is usable and that I could contribute to. 

This would probably end up with such tracks dying off or never coming to be in the first place because people would never see them and never contribute to them.

Thus I guess this is a feature request that the upcoming and planned language tracks be displayed somehow, both to users signed in and not signed in.

**Comment by Stargator** [comment]
I agree, I noticed this awhile ago when I tried v2, but dismissed it as v2 was still a prototype.

It would be great to have the Dart track listed given how close it is to launching :smile:

**Comment by kytrinyx** [comment]
Yes, agreed—this is in the works.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
