### ISSUE TITLE
Merge settings and preferences

### ISSUE THREAD

**Issue by wolf99** [exercism/v2-feedback#115]
In the logged in user menu (clicking on my profile icon at top right), what is the supposed difference between "Settings" and "Preferences"? 

To me these terms pretty much mean the same thing with regards to a website. Communications preferences vs communications settings seems a pretty small distinction. The button on the *preferences* page even says "Save *settings*". 

Perhaps this is intended to accommodate potential growth in each of these categories? If so I would still recommend consolidating to one menu, the resulting page then having several sub-pages - see GitHub Settings for a great example!

**Comment by iHiD** [comment]
@wolf99 Thanks again.

> Perhaps this is intended to accommodate potential growth in each of these categories? 
Yeah, I'm expecting both pages to expand a lot. I totally agree that they both fall under settings. However, I like someone easily being able to get to the menu where they can turn off getting spammed by emails. The button should probably say "communication preferences" to make that clear (similar to facebook - see below).

Let's see how these pages expand and then revisit this as part of a future beta-iteration. I'll also raise this with @nicolechalmers to dig into more. That sound ok?

<img width="205" alt="screen shot 2017-10-02 at 20 26 45" src="https://user-images.githubusercontent.com/286476/31095323-5c3d90a8-a7b0-11e7-9a53-c83c1da5fd17.png">

**Comment by iHiD** [comment]
I'm going to close this for now but feel free to reopen in the future if the pages don't expand enough :)
