### ISSUE TITLE
Footer doesn't stick to the bottom of short pages

### ISSUE THREAD

**Issue by wolf99** [exercism/v2-feedback#116]
On pages that aren't long enough to fill the browser window, the footer lifts up away from the bottom leaving a pile of white-space underneath, instead of extending the white-space above as is normally the expected style for webpages in general. An example is the user account preferences page.

**Comment by iHiD** [comment]
Thanks. Will fix.

**Comment by iHiD** [comment]
This is fixed on master. Thanks again for reporting.
