### ISSUE TITLE
sign up | Log in links dont follow window edge

### ISSUE THREAD

**Issue by wolf99** [exercism/v2-feedback#117]
The links for sign up and log in, on all pages, when not signed in do not follow the right hand browser window edge as it drags in (check www.stackoverflow.com for an example). 

Perhaps this is by design. If it is, one argument against it is that the browser can be at the size that the links do not show when a visitor sees the page, yet the other content above the fold on the front page (the programmer image and the intro blurb) is aligned or moved so that it is still visible. This kind of gives the impression that there is no need to expand the window to find those links... Why would a user expand a window to find links they don't know are there, especially when the rest of the design indicates that the page has sized everything into the window as it is?

**EDIT:** Just noted that there is of course a big purple button under the intro blurb for sign up... 🙄. Point probably still stands in general and for the log in link I think.

**Comment by iHiD** [comment]
Hi @wolf99 - thanks for reporting.

The website isn't currently responsive. We decide not to work on this until we have a final cut of it that is production-ready.

Interestingly, StackOverflow isn't either - it just has a smaller minimum frame size than we do. If I go any smaller than this, then the buttons disappear:

<img width="709" alt="screen shot 2017-10-02 at 13 36 25" src="https://user-images.githubusercontent.com/286476/31077520-bbab9484-a776-11e7-925c-d7bd706ac36d.png">

I'm going to close this for now, as it's on our long-term product roadmap, but not going to get fixed during prototype stage. Thanks again for reporting, though.
