### ISSUE TITLE
The pitch seems like it changed

### ISSUE THREAD

**Issue by samir-majhi** [exercism/v2-feedback#119]
The original website exercism.io looked like a fun project. The new one looks like a commercial product that someone wants to sell you. 

1. 
The pitch on the original website was:
"Level up your programming skills
Download and solve practice problems in over 30 different languages.
Submit the solution to the site for feedback (beta).
For code newbies and experienced programmers."

Which is short, engaging, and to the point.

The new one says:
"Code Practice and Mentorship for Everyone
Level up your programming skills with 1,908 exercises across 38 languages, and insightful discussion with our dedicated team of welcoming mentors. Exercism is 100% free forever. "

That's not very inviting. And users don't care how many exercises there are (as long as there are more than say 20)
Granted, the original site could be made a little bit more structured. But the new one stripped the website of all it's character. Exercism isn't another Udemy or Codeacademy.

2. 
In the original site, "how do you use it" is on a separate page. Which is great because the landing page's purpose is to get you interested, not tell you how it works. In the new site, the 5 steps of how it works makes it seem like a lot of work. That puts you off a little bit. When I joined, in my head, it was only a bunch of exercises that I could do. The submitting and discussions part was a delightful feature that I discovered later.

**Comment by iHiD** [comment]
@samir-majhi

Thanks for commenting. I basically disagree with everything you say and am not sure where to go with this conversation other than to say that :)

> The pitch seems like it changed

It has. That's the whole point.

> Which is short, engaging, and to the point.

While you might not like the second, they're both short, engaging and to the point. They're 200 chars vs 217 chars. 

> That's not very inviting. 

> And users don't care how many exercises there are (as long as there are more than say 20)

> Which is great because the landing page's purpose is to get you interested, not tell you how it works. 

I disagree with all three of those statements.

> When I joined, in my head, it was only a bunch of exercises that I could do. The submitting and discussions part was a delightful feature that I discovered later.

And so if you'd been looking for mentorship originally then you probably wouldn't have joined, which is the crucial thing we are trying to address.

I think we'll have to agree to disagree here.

**Comment by Stargator** [comment]
I agree with this part:
> In the original site, "how do you use it" is on a separate page. Which is great because the landing page's purpose is to get you interested, not tell you how it works. In the new site, the 5 steps of how it works makes it seem like a lot of work.

Too much information on one page can be overloading and then looking at steps when you haven't been sold is a solid point.

But the reverse is true, I may look at a page and feel like I need more details, how would I know where to go from there. Having the steps on the first page highlights the type of actions you would have to be willing to engage in.
