### ISSUE TITLE
[nextercism][cli] Unexpected output and error messages are shown while downloading exercises

### ISSUE THREAD

**Issue by ilya-khadykin** [exercism/v2-feedback#12]
After downloading `nextercism` CLI and issuing the following command on Windows x64:
```ps
PS D:\Github\contributions\nextercism-windows-64bit> .\nextercism.exe download hello-world

```
without setting API token from my profile it returns an empty string.

Also, after correctly setting up the token it still shows an unexpected error message **when you don't specify expected arguments (track `--track=r`)**:
```
PS D:\Github\contributions\nextercism-windows-64bit> .\nextercism.exe download hello-world
2017/08/19 00:11:12 The filename, directory name, or volume label syntax is incorrect.
```

**Comment by kytrinyx** [comment]
Thanks for the heads up, @m-a-ge!
