### ISSUE TITLE
Languages are hard to find on home page

### ISSUE THREAD

**Issue by samir-majhi** [exercism/v2-feedback#120]
It took me a lot of time, and hovering over the icons to find Ruby.
New coders probably won't recognize the icon of their language as quickly as experienced coders will.

Possible solutions:
1. Use the original colors of the icons
2. Write the language names below the icons so that I can do a CTRL+F

**Comment by NobbZ** [comment]
What page are you talking about?

The page I see, has written the name of the language on the right of the Icon on the same card.

https://v2.exercism.io/my/tracks

![names-are-there-already](https://user-images.githubusercontent.com/58951/31602011-ff9cc272-b25b-11e7-9583-85f7bccb97a3.png)

I'm not aware of any other page in the current version of v2 which lists the languages...

**Comment by samir-majhi** [comment]
I'm talking about the home page. Without signing in.
https://v2.exercism.io/
![image](https://user-images.githubusercontent.com/32010530/31608748-200fd200-b28f-11e7-8c30-62b52018fd9b.png)

**Comment by NobbZ** [comment]
Yeah, I do understand now.

And I do feel your pain with that. But as the entrypage is more a showcase, I do think the presentation is fine as it is, **but** we should provide a link there to a more detailed overview which shows the languages cards similar to those tracks a loged in user hasn't started yet.

**Comment by samir-majhi** [comment]
How about arranging them alphabetically for easier search?

It currently is randomized on each reload which seems like a way to sidestep fights over whose favorite language should appear first.

**Comment by kytrinyx** [comment]
@samir-majhi thank you for your feedback.

The homepage is about tantalizing—it's not meant to be a systematic overview. We're not sidestepping language wars, we're just giving a fun visual overview of the richness and variety.

The language tracks page _is_ a systematic overview and is alphabetized. http://v2.exercism.io/tracks

**Comment by samir-majhi** [comment]
@kytrinyx Thanks for explaining. Is there a strong reason why the **language** list is randomized on the home page?
The random **person** changes is brilliant and adds a lot to the personality as well as making the site more interesting. 
But the same doesn't apply to the randomness of **language** listing. Is the purpose of it to keep the site looking fresh? Or to hint that language and exercises keep getting updated? I'm curious to know the value we're getting with randomization of languages. Because the cost we're paying is ease of use.

As a corollary, what's the argument against listing the languages alphabetically or in some other easy to find way?

**Comment by kytrinyx** [comment]
The display on the homepage is a visual indicator of all that Exercism has to offer. While we're not sidestepping fights (as you suggested), we deliberately do not want to prioritize any language over the other on the homepage. There is also some joy in trying to spot your logo and see what else you stumble across.

> what's the argument against listing the languages alphabetically or in some other easy to find way?

We have the languages listed alphabetically on the tracks page.

**Comment by samir-majhi** [comment]
@kytrinyx Thanks for the explanation. I'm closing the issue.
