### ISSUE TITLE
Installation instructions only available for Mac?

### ISSUE THREAD

**Issue by drueck** [exercism/v2-feedback#122]
I used to use exercism quite a bit, and wanted to check out the v2 beta, so I just logged in for the first time today. I didn't know how to get the cli installed, or even if that's how v2 worked, so I eventually found my way to a button with a walkthrough of how to get started, but I immediately hit a roadblock. It popped up and the first question it asked was "What OS do you use?" and the only option was Mac. I'm on linux, and the instructions talk about homebrew, so I couldn't really proceed any further. I tried to look around the rest of the UI for other places that talked about downloading the cli or any other initial setup info and couldn't find them.

Here's a screenshot of what I got for the first question of the walkthrough:

![choose-mac](https://user-images.githubusercontent.com/689382/32817249-8f880d16-c971-11e7-919e-9959aff5d045.png)

I would be happy to help with writing up installation instructions for linux if that help is needed. First I'd have to learn how to install it in the way that you would like users to do so in this new version, however.  :)

Thanks. And sorry if this issue has been covered elsewhere and I just missed it. I've been out of the loop of exercism for too long!

**Comment by NobbZ** [comment]
Basically it is download and copy to PATH. Currently there are no deb or rpm or other packages available for v3.0

**Comment by Insti** [comment]
I can't even find the guide :(

**Comment by kntsoriano** [comment]
@drueck Hello! Yes, you are correct. Unfortunately, only Mac has installation instructions written for now. The next step is to reach out to the community and to find volunteers to help write installation instructions for the other platforms, such as Windows and Linux. I'm happy to hear that you are willing to help :)

As for installing the command line client on your Linux machine, @NobbZ is correct. You need to download the client and copy it to `PATH`. If you'd need more help, please feel free to reach out. This alone helps in building the FAQ section of the walkthrough which would be useful for everyone encountering problems when installing the CLI.

**Comment by rpottsoh** [comment]
The [latest](https://github.com/exercism/windows-installer/releases) release of the Windows Installer for the CLI is already setup to properly install the V3 client, once it is released.  For the time being the installer continues to install the latest release of the CLI for Windows.

Clearly documentation needs to be added to the V2 site regarding Linux and Windows installation of the CLI.  

The latest [pre-release](https://github.com/exercism/cli/releases) version of the CLI may only be downloaded and installed manually.

**Comment by drueck** [comment]
Thanks, all. I was able to find and install the cli, due to familiarity with the github repo structure and where things were located and how they worked with the existing site. If nobody else is working on instructions for installation on linux, I could help write those. If you all would like me to, should I start a new issue to discuss the proposed instructions (linux is so open-ended as far as how you might install it), or just submit a PR when I have some written and we could discuss there?

**Comment by NobbZ** [comment]
I do not think we should write instructions that cover the current manual install, instead we should prepare instructions that are only correct after release.

We should talk about RPM and DEB packages and repositories as if they were already there and mention manual install only as a fallback option.

**Comment by drueck** [comment]
Oh, ok. Yeah, installation via packages would be a much better user experience. Well, in that case I'll let those who know more about what's going on work on that whenever it's appropriate to do so. I'm a little out of the loop on v2.  :)  Should I go ahead and close this issue, or leave it open as a TODO?

**Comment by kntsoriano** [comment]
@drueck It'd be great if you could write the walkthrough for the installing the CLI on Linux manually. While I agree it'd be a better user experience to install via packages, it'll also be helpful to have instructions to install manually as there may be situations where this installation option would be preferred :)

You can start contributing by sending your installation instructions as a PR to this repository: https://github.com/exercism/interactive-cli-walkthrough. I've added a small contributing guide there to get you started, but it's still in rough state, so please don't hesitate to ask questions by opening issues in that repository!

**Comment by drueck** [comment]
@kntsoriano Sounds good. I'll see if I can write something up this weekend if I get a chance.

**Comment by kntsoriano** [comment]
@drueck Thanks for helping!

**Comment by drueck** [comment]
Hey @kntsoriano and all, I'm sorry I haven't made time yet to work on this. To be honest I'm just not feeling very motivated to work on it. I apologize for saying I would and then backing out. Just wanted to let you all know, so someone else with more time and/or motivation could pick it up if they want and know they aren't stepping on my toes.

**Comment by kntsoriano** [comment]
@drueck No problem! Thanks for letting us know :)

**Comment by iHiD** [comment]
This is sorted now so I'll close this. Thanks everyone :)
