### ISSUE TITLE
Version of test suite downloaded differs from version displayed in website UI.

### ISSUE THREAD

**Issue by drueck** [exercism/v2-feedback#123]
I tried out the v2 beta for the first time last night, downloading the hello-world exercise for Elixir and submitting it. The test suite that was downloaded only had _one_ test case, so I made that test pass and submitted the solution. However, when I viewed the solution on the website and looked at the test suite on the solution page, it showed _three_ test cases. I went back and double-checked, and sure enough, the two files were different. I tried re-downloading the exercise, but it gave me the same test file with just one test case.

Additional info: I'm an existing user of exercism and have completed quite a few solutions in the Elixir track, but had never done the hello-world exercise, because it didn't exist when I started the track back in the day. Not sure if that has any relevance, but figured I'd include all potentially applicable info.  :)

**Comment by Insti** [comment]
v2 is showing old data.

Not much visible has happened on v2 for the last few months and in that time the v1 exercise tests have been updated, but these changes have not made their way to v2 yet.

**Comment by drueck** [comment]
Gotcha. Thanks.

**Comment by kytrinyx** [comment]
Thanks for the discussion. This is totally on me—I have a data migration script that we haven't run nearly often enough. We'll be doing a new migration shortly.
