### ISSUE TITLE
Informing students of test suite updates

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-feedback#125]
On V1 there is no way to inform students that the test suite for an exercise has been updated.  I think this would be a nice addition to V2. 

If V2 can track when a student last fetched an exercise it should then be able to display an indicator next to the exercise on the site to catch the students attention.  The indicator should be intuitive to mean that the exercise has been updated and that they should re-fetch the exercise.  An alternative approach might be to email the students that have fetched a particular exercise when those exercises have been updated....  I am more in favor of the first idea personally.

@kotp put it this way:
> Something a lot less than an announcement, something slightly more than silence.

**Comment by kytrinyx** [comment]
Thanks for the suggestion, @rpottsoh

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
