### ISSUE TITLE
Cannot expand solution box

### ISSUE THREAD

**Issue by martinfreedman** [exercism/v2-feedback#126]
This is a great feature in v1 with the sw ne arrows button.  I tried double clicking on the latest solution tab but that does nothing. I hope this is the plan for the final release. I look at the solution on different devices and the expand feature is invaluable

**Comment by kytrinyx** [comment]
Thanks, @martinfreedman

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
