### ISSUE TITLE
Cannot tell if there are any comments on other iterations

### ISSUE THREAD

**Issue by martinfreedman** [exercism/v2-feedback#128]
I cannot see if there are comments on other iterations, again a feature I would miss. 

I will stop adding issues for now. And await feedback on these and if this is the correct place to discuss the design questions.

The new design looks great but  not sure about all this loss of functionality I have seen so far.

**Comment by budmc29** [comment]
There is nothing wrong with adding issues, as long as you search for any issue that is related in the opened and closed existing issues.
Alternatively you can create a general issue and add comments in there with multiple issues and depending on the discussion we can see what's to do.

**Comment by iHiD** [comment]
> I cannot see if there are comments on other iterations, again a feature I would miss.

Are you refering to this or something else on v1?

<img width="776" alt="screen shot 2018-01-17 at 13 20 31" src="https://user-images.githubusercontent.com/286476/35044683-3820dae0-fb89-11e7-81ca-7db3f35b2be7.png">

> I will stop adding issues for now. And await feedback on these and if this is the correct place to discuss the design questions.

All your comments are appreciated :)

**Comment by martinfreedman** [comment]
@iHiD Yes this is exactly what I am referring to that appears lacking in v2

**Comment by carolineschnapp** [comment]
I very sorely miss that feature as well that @iHiD is showing.

In the current website, it's quite obvious iterations exist, and if someone has commented on a past iteration, and you've made a change based on their feedback, you can easily go back to the old iteration to find their original comment, and each iteration tab has a bubble indicating how many comments are attached to it. 

I understand fully how comments are tied to a particular iteration, and should not be the same conversation thread for all iterations. 

However, on the beta site, it took me forever to locate the iteration navigator at the top right so I wrongly assumed that once I submit a new iteration based on some feedback I forever lose all past feedback and iterations. I thought it was just like starting from scratch. 

Heck, I wanted to respond to the mentor, and I did not even remember their name at that point! It took me days to discover that nothing was erased. I felt like I was being so rude, taking on feedback, and never responding.

Both iterations, and how many comments are attached to them, should be more discoverable, in my opinion.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
