### ISSUE TITLE
[nextercism CLI] `nextercism submit` bugs on Windows

### ISSUE THREAD

**Issue by jonmcalder** [exercism/v2-feedback#13]
From Command Prompt and Powershell:

nextercism CLI works both without args and when specifying the full path, but only if `\` separators are used
* Neither `/` or `//` seem to work as filepath/directory separators
* The file path is also case sensitive
* The combination of the above seems overly strict and problematic - we need something more friendly (especially for those who are new to the command line)

From Git Bash:

* Running `nextercism submit` from within exercise directory does not work. The error returned is: `. not within workspace`
* Including the full filepath works, but is again subject to the strict rules mentioned above

**Comment by kytrinyx** [comment]
> The combination of the above seems overly strict and problematic - we need something more friendly (especially for those who are new to the command line)

❤️ ❤️ ❤️ Yes!

I'm going to need some help getting Windows stuff tested, and finding all these unfriendly sharp edges is incredibly helpful. I'm probably going to have to ask you some additional questions once I start digging into this.

**Comment by jonmcalder** [comment]
Cool - happy to help further. Just ping me when the time comes!

**Comment by amoradell** [comment]
I had a similar problem when downloading elm first exercise 
d:\exercism>cli\nextercism download hello-world --track elm
2017/08/19 22:14:51 open d:\exercism\elm\hello-world\ **tests** \Tests.elm: The system cannot find the path specified.

tests directory wasn't created. instead it's a file.

d:\exercism>dir elm\hello-world /AH /AA
19/08/2017  22:23               206 .solution.json
19/08/2017  22:23               344 elm-package.json
19/08/2017  22:23               673 HelloWorld.elm
19/08/2017  22:23               337 package.json
19/08/2017  22:23             1 401 README.md
**19/08/2017  22:23                 0 tests**

**Comment by NobbZ** [comment]
@amoradell probably the same issue as in #9

**Comment by amoradell** [comment]
@NobbZ sorry, I saw Windows...
I duplicate on #9

**Comment by kytrinyx** [comment]
@amoradell the good news is we know exactly what is causing it and will have a fix for you soon 🌷

**Comment by amoradell** [comment]
Thanks, I will test on parallel with v1 on same track

**Comment by kytrinyx** [comment]
@jonmcalder I think I have fixed the `. not within workspace` issue in the 3.0.0-alpha.3 release: https://github.com/exercism/cli/releases/tag/v3.0.0-alpha.3

**Comment by jonmcalder** [comment]
@kytrinx Ok I have retested with v3.0.0-alpha3 in command prompt, powershell and git bash on Windows:

Unfortunately I have to report that none of the above mentioned issues seem to be resolved in any of these shells... 😢

**Comment by kytrinyx** [comment]
@jonmcalder I'm going to open three different issues for this so that we can talk about them all separately. I didn't do anything to address the first two, only the one with the `. not in path`.

**Comment by kytrinyx** [comment]
Closing this in favor of:

- https://github.com/exercism/v2-feedback/issues/42
- https://github.com/exercism/v2-feedback/issues/43
- https://github.com/exercism/v2-feedback/issues/44

**Comment by jonmcalder** [comment]
Ok no worries. Yes I gathered that, but just tested for all three issues in case. Agree its better to split them up to keep track though.
