### ISSUE TITLE
Comment,Liked Solutions, Notification History and search

### ISSUE THREAD

**Issue by martinfreedman** [exercism/v2-feedback#130]
Where can I find  give me a history of my comments both generally and per user or per exercise?  

How can I search and filter my comments?

Where can I find a list of solutions I have liked. 

Where is my notification history?

How can I search and filter it?

**Comment by ErikSchierboom** [comment]
@martinfreedman These are actually several issues, right? If so, I think it would be better to create separate issues for them, as that makes tracking them easier.
