### ISSUE TITLE
How can I find my history of comments

### ISSUE THREAD

**Issue by martinfreedman** [exercism/v2-feedback#131]
How does one find one's history of comments, presumably with metadata such as exercise, iteration and  addressee? (see #130)

**Comment by martinfreedman** [comment]
See #130

**Comment by kytrinyx** [comment]
We've got a number of discussions going to improve the experience of commenting, giving feedback, etc. These have not yet been implemented.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
