### ISSUE TITLE
How can I manage my comments?

### ISSUE THREAD

**Issue by martinfreedman** [exercism/v2-feedback#133]
Pending a positive outcome to #131 and #132, how do I delete or copy comments (editing old comments IMV should not be allowed once responded to but not pursuing that here for now) (See also #130)

**Comment by ErikSchierboom** [comment]
I just bumped into the same issue, where I cannot delete a comment.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
