### ISSUE TITLE
Where is my notification history

### ISSUE THREAD

**Issue by martinfreedman** [exercism/v2-feedback#134]
Once I have responded to a notification, it disappears. I was expecting any v2 to provide a notification history with metadata of userid, exercise, likes flags and date. (see also #130)

**Comment by kytrinyx** [comment]
At the moment, notifications are implemented similarly to how GitHub does them. As soon as you've read them, they go away.

**Comment by HarrisonMc555** [comment]
This could probably wait until after the v2 launch, but I personally **really** prefer Facebook's style of persistent notifications, at least until they "scroll out of view". I've had several times in using exercism v1 where I clicked on a notification but accidentally closed the window without looking at _all_ the notifications.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
