### ISSUE TITLE
How can I find solutions that I have like?

### ISSUE THREAD

**Issue by martinfreedman** [exercism/v2-feedback#136]
There are new like flags in v2 compared to just 1 in v1. Still I was expecting the ability to list those solutions that I have liked, with the ability to filter per userid or exercise for example. (see also #130)

**Comment by iHiD** [comment]
On the drop down at the top right:

<img width="248" alt="screen shot 2018-01-29 at 12 31 48" src="https://user-images.githubusercontent.com/286476/35627780-e1761cdc-0691-11e8-87bf-4c8695f58336.png">

**Comment by martinfreedman** [comment]
Thx but how do I see who else has liked it, as you can in v1?
