### ISSUE TITLE
Cannot log in via Chrome via Github

### ISSUE THREAD

**Issue by martinfreedman** [exercism/v2-feedback#137]
I can log in via Github on Firefox. 

Just updated to latest Chrome and still no difference, same with Windows 10 updates 
Windows 10: Version	10.0.16299 Build 16299
Chrome: Version 63.0.3239.132 (Official Build) (64-bit)

What happens is that the the "Welcome to Exercism Beta" just pops up again and I am still
not logged in.

**Comment by budmc29** [comment]
In situations when something like this happens to me it's usually a plugin.

If you did not do it already, can you try the same process with a incognito session (making sure no plugin is enabled?).
