### ISSUE TITLE
Typo in README & Suggestion

### ISSUE THREAD

**Issue by DavidMellul** [exercism/v2-feedback#138]
Hello ! 

I have discovered exercism last week and I really enjoyed playing and learning with it.

**First :  There is a typo in the README (2 times 'or' word)**

![image](https://user-images.githubusercontent.com/21335017/36342281-454e5c66-13fc-11e8-88e8-a523712de3ff.png)

**Second : I think it would be valuable and overall very useful to let users send feedback about an exercise.**

*My point* : I believe that sometimes the learning curve isn't appropriate. e.g. Bowling after Grade School in Ruby was a real pain hahaha. If I could have given my feedback, I would have stated several points such as :

- Rules could've been explained with more details (the README didn't give enough information to pass all the tests without having to run each test one by one to understand how we were expected to do it)

- The exercise could have come later according to its difficulty.

With that comes a side question : As a maintainer of the project, is one enabled to change the order of the exercises in a given track ? 

It's one of my first PRs 👼  Hope it helps 👍

**Comment by kytrinyx** [comment]
Thanks for your feedback (I've fixed the typo in the README).

> I think it would be valuable and overall very useful to let users send feedback about an exercise.

Yes, it would be very valuable to get feedback. People can always go provide feedback in the repo for the language track, but the bar is higher for that than to give feedback in place, so it would be worth considering.

> Rules could've been explained with more details (the README didn't give enough information to pass all the tests without having to run each test one by one to understand how we were expected to do it)

Reading the tests, and running them is a very big part of solving the exercise—the README isn't always intended to be a complete spec. But if the README is confusing, then it's worth giving feedback and helping clarify.

The README is generated from a general description, which lives in https://github.com/exercism/problem-specifications/blob/master/exercises/bowling/description.md

> The exercise could have come later according to its difficulty.

If you want to suggest this, then you can do it in http://github.com/exercism/ruby

>  As a maintainer of the project, is one enabled to change the order of the exercises in a given track ?

Yes, the maintainers of each track decide the order.

Thanks 🌷
