### ISSUE TITLE
Display order of exercises in track

### ISSUE THREAD

**Issue by ardrigh** [exercism/v2-feedback#139]
I just tested submitting to the Go track for version 2, and I noticed the track items aren't activated in the order they are displayed in the path vertically.

The first exercise in the Go track is "Two-fer". The second exercise displayed is "Clock". The third displayed is "Hello World". 

If I manually complete the "Two-fer" exercise, it activates "Hello World", skipping over "Clock" in the vertical path. The progression box shows I have completed 1 out of 18 core exercises.

I am not sure if this is a bug with the track configuration or just the way it's displayed on the webpage https://v2.exercism.io/my/tracks/go  but a user wouldn't expect core exercises to get skipped over when displayed as a vertical progress path.

**Comment by kytrinyx** [comment]
>  a user wouldn't expect core exercises to get skipped over when displayed as a vertical progress path.

Agreed—there's something funky going on. We do have an open issue that has to do with ordering, and this might be related to that, but I'm going to add your details to it so we are sure to fix it either way.

Thanks!

**Comment by iHiD** [comment]
This is now fixed on master. Thanks for reporting!
