### ISSUE TITLE
[nextercism] [mentoring] It's hard to spot to what language student's solution is related to

### ISSUE THREAD

**Issue by ilya-khadykin** [exercism/v2-feedback#14]
If you are part of several track as a mentor it isn't clear to what language solution is related to. Language icon is too small

![image](https://user-images.githubusercontent.com/6649477/29479635-254f6050-847c-11e7-8649-bef692bde7d4.png)

**Comment by kytrinyx** [comment]
Thanks @m-a-ge, that's a good point. I also wonder what this page is going to look like when the volume of submissions grows dramatically.

I've added this to our product/ux list of things to consider. 🌷

**Comment by rpottsoh** [comment]
I stumbled on this issue this morning.  I joined elm yesterday, as part of testing the site.  This morning I entered the Mentor interface to see that a hello-world submission needed a comment....  (I forgot about elm) and assumed it was a delphi submission, however the README for the exercise was wrong....  Obviously it is correct for elm....  There just is nothing in our face to indicate the track the submission is for.

![image](https://user-images.githubusercontent.com/6978003/29520167-19cf2f34-864e-11e7-873c-0e83bdc909cb.png)

**Comment by iHiD** [comment]
@m-a-ge We've made the icons bigger and inverted the colours to help make this more obvious.
@rpottsoh We've added the language clearly in the title bar of the solution page.

I'm going to close this for now. If it continues to be a problem for you, please reopen it :)
