### ISSUE TITLE
Thoughts on Mentors -> Solution -> Instructions tab 

### ISSUE THREAD

**Issue by emcoding** [exercism/v2-feedback#141]
`/mentor/solution/:id`
- On the Instructions tab: I'd prefer to have all the exercise related info together. Currently, the source of the exercise is at the bottom of the info, after the general submission info. (Which made me read all the submission info, to see if I missed other exercise related info.)
BTW I wouldn't mind if the submission info is omitted in this tab. 
- When reviewing a solution, I'd like to see (a link to) the student's other solutions (different exercises), to get a feel for their level and how they respond to feedback. So I can finetune my feedback.   
- As long as we don't have the 'community favorites', I'd like to have a link to my own solution, for a quick reference.

**Comment by iHiD** [comment]
Good points. I'll pass these to the product team to discuss :)

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
