### ISSUE TITLE
Status updates

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#142]
Lately, I have been wondering about the lack of status updates on the v2 prototype. There has not been much information on the progress of the prototype, is there any specific reason why that is? Also, there have only been [**two** commits](https://github.com/exercism/prototype/commits/master) to the prototype repository, which begs the question: is the prototype still being actively worked on?

Please don't take this as criticism of any kind, I am only asking because I am quite excited about the v2 version.

**Comment by NobbZ** [comment]
Well, there was a recent comment in another issue, that there will be a meeting this week and that we will get informed after:

https://github.com/exercism/v2-feedback/issues/89#issuecomment-386588945

**Comment by ErikSchierboom** [comment]
Ah, totally missed that!

**Comment by iHiD** [comment]
Hello. So I'm currently sitting with @nicolechalmers and @kytrinyx and we're spending a couple of days planning everything out. We're aiming for a launch within the next two months but want to ensure we get everything right so putting together a plan to make that happen. Thank you both for your excitement :)
