### ISSUE TITLE
Profile field spacing on Firefox/Linux

### ISSUE THREAD

**Issue by chastell** [exercism/v2-feedback#143]
The label spacing for the Twitter/GitHub/Medium handles in Firefox 60 on Linux is off, looks like due to the width of the (fallback?) font:

![firefox borderised](https://user-images.githubusercontent.com/56633/39955799-b7c9f668-55d5-11e8-85f1-29ca1ed8fcde.png)

This is not the case in Chromium 66, which looks fine:

![chromium borderised](https://user-images.githubusercontent.com/56633/39955803-c9739f54-55d5-11e8-9af6-69b4e97ad663.png)

**Comment by iHiD** [comment]
Helpful. Thanks. As a FYI, we recently changed all the fonts to more
"accessible" ones so we need to do a full pass to realign some things that
have broken as a result. Knowing about specific cases like this is very
helpful though, especially when they change based on browser!

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
