### ISSUE TITLE
vertical sizing and scrolling bugs

### ISSUE THREAD

**Issue by bdjnk** [exercism/v2-feedback#145]
There are many bugs around the sizing and scrolling of nested content boxes.

I'm experimenting on a MacBook Pro (15-inch, 2017) running macOS High Sierra, Version 10.13.4 (17E199)

The last line of the Mentor Discussion Write editor is cut off using Google Chrome 67.0.3396.62 (Official Build) (64-bit)

http://recordit.co/tSpuc7F9AP

Similar to the above, plus the Test Suite viewer has a small scrollable distance which feels buggy, using Firefox 60.0.1 (64-bit)

http://recordit.co/9CckTGelte

These problems, and many similar problems I've encountered, could be solved by not using nested scrollable boxes, but instead allowing the page scroll to do it's job.

In my experience as a front-end developer, and by my personal preference, I find nested scrolling containers to be a very poor UX.

**Comment by rpottsoh** [comment]
No worries.  Several issues have been raised that pertain to oddities in scrolling behavior.  I think the team is on it.  See if any of [these issues](https://github.com/exercism/v2-feedback/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+scroll) covers what you have experienced.

**Comment by kytrinyx** [comment]
@bdjnk Thanks so much for finding these. I actually think we thought we had tackled the scrolling issues, so these are really helpful details.

**Comment by iHiD** [comment]
@bdjnk Thanks for posting and especially for doing the videos.

> The last line of the Mentor Discussion Write editor is cut off using Google Chrome 67.0.3396.62 (Official Build) (64-bit)

I'll debug this.

> Similar to the above, plus the Test Suite viewer has a small scrollable distance which feels buggy, using Firefox 60.0.1 (64-bit)

I don't think this one is a bug personally - it's as per design (which I appreciate you don't like). The content is bigger than the window, so the browser shows scrollbars. If the code was one line longer or shorter, or the browser a few pixels shorter or longer, this wouldn't feel buggy. It's unfortunate that it's just a couple of pixels too long so the scrolling feels unnecessary.

> These problems, and many similar problems I've encountered, could be solved by not using nested scrollable boxes, but instead allowing the page scroll to do it's job. In my experience as a front-end developer, and by my personal preference, I find nested scrolling containers to be a very poor UX.

I totally see where you're coming from. The problem with just allowing a page to scroll, though, is that it means it's impossible to see the code and the box you're typing into at the same time. While I agree that nested scrolling isn't ideal, I find the the functional tradeoffs of being able to see the code that you are commenting on outweights the aesthetic of not having nested scrolling. Maybe we change it so the LHS is full height on the RHS sticks to the page and sticks with it instead. I'll have a play if I get time before launch.

**Comment by bdjnk** [comment]
@iHiD I would be strongly supportive of using [`position:sticky`](https://caniuse.com/#feat=css-sticky), and if necessary [stickyfill](https://github.com/wilddeer/stickyfill), along with [`max-height: 100vh`](https://www.w3.org/TR/css3-values/#viewport-relative-lengths), on the comment box. The would allow the solution to expand as necessary within the page scroll while maintaining the desired code context.

**Comment by bdjnk** [comment]
If you'd like to see how that works in practice, I quickly built [this example](https://codepen.io/bdjnk/pen/QxEogE). Paste something lengthy into each editable div and scroll around.

**Comment by aspanu** [comment]
Came here to report this issue as well. For me, the scrolling bug occurred when writing feedback as a mentor. You can see this screenshot as an example. This was on Chrome Version 67.0.3396.79 on OS X.
![image](https://user-images.githubusercontent.com/3299254/41806140-f57d2b08-766c-11e8-80d7-842647be5f7d.png)

**Comment by rpottsoh** [comment]
> The last line of the Mentor Discussion Write editor is cut off 

worked on a long comment today and came across this issue as well.

**Comment by iHiD** [comment]
> The last line of the Mentor Discussion Write editor is cut off

This is fixed on master now but not deployed. Just FYI.

**Comment by iHiD** [comment]
> If you'd like to see how that works in practice, I quickly built this example. Paste something lengthy into each editable div and scroll around.

Thanks @bdjnk

**Comment by iHiD** [comment]
Closing this for now as I've removed all funky scrolling. Will revisit when the other bugs are sorted. Thanks.
