### ISSUE TITLE
Code sample has vertical scroll on Firefox

### ISSUE THREAD

**Issue by tuvokian** [exercism/v2-feedback#148]
Minor issue, but on the track pages (e.g. https://v2.exercism.io/tracks/r) the code sample box has a vertical scrollbar. On Windows 10, I noticed this behaviour in Firefox 60 & Edge 42.17134.1.0, but not on Chrome 67.

**Comment by kytrinyx** [comment]
Thanks @zacchaeusluke, I'm passing this to @iHiD for triage, as he's addressed a few scrolling issues in the past.

**Comment by iHiD** [comment]
@zacchaeusluke This is fixed on master now. The issue arose due to us changing fonts. Thank you for reporting 💙
