### ISSUE TITLE
Improve error message on trying to download locked solution

### ISSUE THREAD

**Issue by kytrinyx** [exercism/v2-feedback#149]
reported by @unused in https://github.com/exercism/cli/issues/571#issuecomment-399515021

The `Error: Solution not found` message shows up when the user has not joined the language track yet. I guess the common case is someone joins a language track before downloading some exercise, yet it might be a good point to improve the UX. [slack ref #testing](https://exercism-mentors.slack.com/archives/CBDHAPPLP/p1529686995000140?thread_ts=1529686855.000469&cid=CBDHAPPLP)

**Comment by kytrinyx** [comment]
@iHiD let's distinguish between trying to download a locked exercise and trying to download an exercise that doesn't exist.

**Comment by iHiD** [comment]
I'm AFK but I believe that the API already give this via the `error[type]` part of the JSON returned with the 404. It's one of `track_not_found`, `exercise_not_found` or `solution_not_found` IIRC where the first two mean incorrect slugs and the later means the person doesn't have an unlocked solution for this exercise.

**Comment by kytrinyx** [comment]
Perfect, thanks!
