### ISSUE TITLE
How to tell who the mentor is once I've joined a track

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-feedback#15]
Once I have joined a track I am no longer able to see all the nice information that is provided on the "join this track" page.  Once I have joined a track I do not see a way to even tell who the track maintainers are.  The only way I see to revisit the "join this track page" is to sign out and then explore the track without signing back in.

**Comment by kytrinyx** [comment]
Ah! I didn't notice this. This is a great catch. I definitely want us to be able to visit any publicly accessible pages even if we are logged out.

I am opening an issue in our product/ux tracker. Thanks so much for raising it 🌻
