### ISSUE TITLE
mentorcism: submitting solution is "difficult"

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-feedback#150]
`mentorcism` cannot find my solution to submit even if I am at that location.  I was using my Windows 7 system at the time.

With the V1 CLI `exercism s uBob.pas` would work fine if I was in the folder where `uBob.pas` was located.  With mentorcism I must:
```text
C:\nextercism\delphi\bob>mentorcism s c:\nextercism\delphi\bob\ubob.pas

C:\nextercism\delphi\bob>
```
It would nicer if:
```text
C:\nextercism\delphi\bob>mentorcism s ubob.pas
```
would work.

There was no response from the CLI when I submitted my solution for `bob`.  The procedure was successful as my solution appears on the site.

---
Here is what I captured from my terminal while trying to use the CLI for the first time with hello-world:

```
C:\nextercism\delphi\hello-world>mentorcism s .
Error: . not within workspace

C:\nextercism\delphi\hello-world>mentorcism s c:\nextercism\delphi\hello-world
You specified a directory, which contains these files:
 [1]  C:\nextercism\delphi\hello-world\HelloWorld.dpr
 [2]  C:\nextercism\delphi\hello-world\uHelloWorld.pas

Press ENTER to submit, or control + c to cancel: 2
Submit cancelled.
Try submitting individually instead.
C:\nextercism\delphi\hello-world>mentorcism s
Error: C:\nextercism\delphi\hello-world not within workspace

C:\nextercism\delphi\hello-world>

C:\nextercism\delphi\hello-world>mentorcism c -s

Config dir:      C:\Users\Ryan Potts\AppData\Roaming\mentorcism
-t, --token      23fXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX83e
-w, --workspace  c:\nextercism
-a, --api        https://mentors-beta.exercism.io/api/v1

C:\nextercism\delphi\hello-world>dir
 Volume in drive C is OS
 Volume Serial Number is 3E0E-CBF1

 Directory of C:\nextercism\delphi\hello-world

06/22/2018  12:43 PM    <DIR>          .
06/22/2018  12:43 PM    <DIR>          ..
06/22/2018  12:41 PM            35,026 GETTING_STARTED_GUIDE.md
06/22/2018  12:41 PM             1,637 HelloWorld.dpr
06/22/2018  12:41 PM             2,029 README.md
03/14/2018  12:06 PM               157 uHelloWorld.pas
06/22/2018  12:41 PM             2,532 uTestHelloWorld.pas
               5 File(s)         41,381 bytes
               2 Dir(s)  17,351,782,400 bytes free

C:\nextercism\delphi\hello-world>mentorcism s uHelloWorld.pas
Error: not in workspace

C:\nextercism\delphi\hello-world>mentorcism s c:\nextercism\delphi\hello-world\uHelloWorld.pas
Your solution has been submitted successfully and has been auto-approved. You can complete the exercise and unlock the next core exercise at https://mentors-beta.exe
rcism.io/my/solutions/3cecd4288e8d474eaa9684fb53efc375

C:\nextercism\delphi\hello-world>
```
Unlike Bob, I received feedback from the CLI once the submission of my solution was complete for Hello World.

----------
repeated from above:
```text
You specified a directory, which contains these files:
 [1]  C:\nextercism\delphi\hello-world\HelloWorld.dpr
 [2]  C:\nextercism\delphi\hello-world\uHelloWorld.pas

Press ENTER to submit, or control + c to cancel
```
This was confusing the first time I saw this.  I know the statement says to ENTER or control + c.  However, my instinct was to type `2` and then ENTER.  This was interpreted as control + c.

**Comment by rpottsoh** [comment]
I think I essentially walked into @kytrinyx comment [here](https://github.com/exercism/cli/issues/568#issuecomment-399477660).

**Comment by kytrinyx** [comment]
Thank you @rpottsoh--there's a ton of work to do to improve the user experience in the client. I think there is definitely some low-hanging fruit. It's going to be my focus for the next 10 days to get the CLI usable.

**Comment by ErikSchierboom** [comment]
I've also been bitten by this.

**Comment by amoradell** [comment]
What I found on windows :
- mentorcism  workspace is case-sensitive so C: and c: are different.

- no feedback when submitting the same solution (using a working directory and a submitting one)

**Comment by rpottsoh** [comment]
Just tested 3.0.0-alpha.10.mentors.  It works the same in CMD as the previous version.  However, it also worked fine in Bash. :1st_place_medal:   Bash performance is on par with CMD performance.  I still have to provide full path information for the file I want to submit, even when I am in the folder that the file to be submitted resides.

**Comment by rpottsoh** [comment]
Just reporting that `submit` for the 3.0.4 version of the CLI is as easy as it was in 2.4.1. 🥇   Thanks @kytrinyx!

Feel free to close this issue if you see no further value in it being open.

**Comment by iHiD** [comment]
Thanks @rpottsoh <3
