### ISSUE TITLE
Mentorcism submit panic

### ISSUE THREAD

**Issue by JoelQ** [exercism/v2-feedback#152]
Looks like there are some hard-coded paths in here? I tried to submit an exercise (after moving the binary 😬 ) an things blew up. I was able to fix the issue by re-configuring things correctly and running a bare `mentorcism submit` in the desired directory.

```
% mentorcism submit hello-world                                    
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x13a1174]

goroutine 1 [running]:
github.com/exercism/cli/workspace.Workspace.Locate.func1(0xc4200de210, 0x23, 0x0, 0x0, 0x150e880, 0xc4201b28d0, 0x0, 0x0)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/workspace/workspace.go:65 +0x44
path/filepath.Walk(0xc4200de210, 0x23, 0xc42012eb40, 0x0, 0x150e880)
        /usr/local/Cellar/go/1.10.3/libexec/src/path/filepath/path.go:401 +0x6c
github.com/exercism/cli/workspace.Workspace.Locate(0xc4200de210, 0x23, 0x7fff5fbff8aa, 0xb, 0x1, 0xc4200b6640, 0x0, 0x0, 0xc4200c8609)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/workspace/workspace.go:100 +0x18c
github.com/exercism/cli/cmd.glob..func6(0x17d8340, 0xc4200ab3f0, 0x1, 0x1, 0x0, 0x0)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/cmd/submit.go:73 +0x168
github.com/exercism/cli/vendor/github.com/spf13/cobra.(*Command).execute(0x17d8340, 0xc4200ab3b0, 0x1, 0x1, 0x17d8340, 0xc4200ab3b0)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/vendor/github.com/spf13/cobra/command.go:649 +0x449
github.com/exercism/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x17d7a40, 0x100620c, 0xc42009a058, 0x0)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/vendor/github.com/spf13/cobra/command.go:728 +0x2d4
github.com/exercism/cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x17d7a40, 0x0, 0xc4200b47a0)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/vendor/github.com/spf13/cobra/command.go:687 +0x2b
github.com/exercism/cli/cmd.Execute()
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/cmd/root.go:45 +0x2d
main.main()
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/exercism/main.go:6 +0x20
```

**Comment by kytrinyx** [comment]
The hardcoded paths are from where it was compiled, and it's not related to where it's trying to run. That said... it shouldn't panic!

>  I tried to submit an exercise (after moving the binary 😬 ) an things blew up.

I'm going to need a wee bit more information than this :)

Do you happen to remember where you moved the binary to and exactly where you were on the file system relative to the exercise that you were submitting?

**Comment by JoelQ** [comment]
I originally put the binary at `~/Code/mentorcism/bin/`. However, once I initialized things and installed the first exercise I saw that mentorcism created its own directory.

For convenience, I then moved the binary to `/user/local/bin` which is on my `$PATH`. I configured my API token again.

Then when I tried to submit via `mentorcism submit hello-world` I got the error shown earlier. After some investigation, it looks like the binary was expecting code to be in a `mentorcism-1` workspace which did not exist (the exercise was in the regular `mentorcism` workspace).

I manually configured the workspace to be `mentorcism` and was then able to submit successfully.

**Comment by kytrinyx** [comment]
The current workspace configuration is a hack intended to tide us over until I can sit down and do it right (before the launch!).

It created `mentorcism-1` because you had the binary in the default location at the time when you ran `mentorcism configure` (it only adds the `-1` suffix if the workspace it's trying to create already exists).

It sounds like the biggest problem is that it panics instead of saying "hey, you're trying to submit hello-world, but your workspace directory doesn't exist so I can't figure out where to find it" and then telling you how to fix the problem.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
