### ISSUE TITLE
mentorcism: Missing exercise images

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#153]
Some exercises don't yet have an image. On the overview page, this leads to an empty white box, which is not that bad. However, on the exercise details page, it displays are broken link:

See for example, [this page](https://mentors-beta.exercism.io/my/solutions/a23ceaf31cca4e879c7f9ec38be18344):

![image](https://user-images.githubusercontent.com/135246/41808628-a691cc5a-76e0-11e8-9da7-5559fee9dd88.png)

**Comment by iHiD** [comment]
Thanks! Exercise icons are in progress but that's definitely a bug in the
solutions page.

**Comment by iHiD** [comment]
Triaged this. Thanks.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
