### ISSUE TITLE
mentorcism: Buttons don't resize correctly on mobile

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#154]
When viewing the mentorcism website on a mobile device (iPhone 6S in this case), buttons are not resized correctly (they are too wide):

![image](https://user-images.githubusercontent.com/135246/41808642-d65f03b2-76e0-11e8-9cda-ad2d2d54cdb4.png)

**Comment by kytrinyx** [comment]
Thanks @ErikSchierboom! We've yet to take a final pass through to adjust all the weirdness that we got when we swapped out the fonts (and I don't actually know if we've gone through the mobile site yet).

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
