### ISSUE TITLE
mentorcism: Mobile device viewport is not correct

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#155]
When viewing the mentorcism website on a mobile device (iPhone 6S), the display is not correct:

![image](https://user-images.githubusercontent.com/135246/41808657-1b06f452-76e1-11e8-9e1b-f5a15198f3ba.png)

It appears to be the case that the viewport is not correct, leading to the mobile browser only displaying a part of the website.

**Comment by kytrinyx** [comment]
Thanks, @ErikSchierboom!

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
