### ISSUE TITLE
mentorcism: Small grammar improvement

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#156]
On the getting started page, it shows the following text:

> "To get started click on the first exercise (Hello World) and follow the instructions"

I think this sentence would read a bit better if a comma was added after "get started":

> "To get started, click on the first exercise (Hello World) and follow the instructions"

![image](https://user-images.githubusercontent.com/135246/41808669-47fcd47c-76e1-11e8-9c2c-729b2a22e7fa.png)

**Comment by rpottsoh** [comment]
I agree with the comma.  I am left wondering if hello world is dynamic or static, hello world is not the first exercise in all tracks I think. 

Sent from my android device.

**Comment by iHiD** [comment]
Agree on the comma. Thanks. PR welcome if anyone wants to get into  the codebase, otherwise get round to it at some point :)

https://github.com/exercism/prototype/blob/master/app/views/my/tracks/_started_modal.html.haml

**Comment by ErikSchierboom** [comment]
> PR welcome

Done! https://github.com/exercism/prototype/pull/73

**Comment by ErikSchierboom** [comment]
@rpottsoh The first exercise appears to be dynamic, according to the template used to render it:

`first exercise (#{@track.exercises.core.first.title})`
