### ISSUE TITLE
mentorcism: Not all resolutions are handled gracefully

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#157]
If one resizes the browser window, at some resolutions things start looking a bit odd with items being truncated instead of being repositioned:

![image](https://user-images.githubusercontent.com/135246/41808699-b4524620-76e1-11e8-9404-8f6ba5d52f48.png)

**Comment by kytrinyx** [comment]
Thanks, @ErikSchierboom! We're going to need to go through the entire site before we launch to catch all the various resizing, responsive, mobile, etc issues.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
