### ISSUE TITLE
mentorcism: Inconsistent capitalization on exercise page sidebar headers

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#159]
The headers in the sidebar menu on the right have inconsistent capitalization:

- Get started
- Been here before
- Still Stuck

The third option should probably be `Still stuck` to be consistent with the other headers.

**Comment by kytrinyx** [comment]
Yes! We'd like to have _sentence case_ for our titles :-)

**Comment by iHiD** [comment]
Triaged for all headers.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
