### ISSUE TITLE
[mentoring] Hello-worlds waiting for mentoring, not able to dismis them

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#16]
In the go-track there are (currently) 3 hello-world submission listed as the first three tasks, there seems to be no way to dismiss them, but I assume the are already "done" since when I enter them, I can only comment, not "approve and comment" as I am able to with some other submissions.

**Comment by kytrinyx** [comment]
This sounds like a bug. Thanks!

**Comment by iHiD** [comment]
This is now fixed. Thanks for reporting :)
