### ISSUE TITLE
mentorcism: Missing tooltip for extra exercise status icon

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#160]
The core exercises have text to show what their status is (in progress, etc.). The extra exercises have an icon, which is less obvious. To help understand which status the icon represents, it should probably have a tooltip of some sort containing the textual status.

**Comment by kytrinyx** [comment]
Yeah, that would be a good improvement. Thanks!

**Comment by iHiD** [comment]
Triaged. Thanks.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
