### ISSUE TITLE
mentorcism: Use descriptive alt tag for profile image

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#161]
The alt tag for the user's image icon is now the user's ID. It is probably better to replace this with the user's account name.

**Comment by kytrinyx** [comment]
Yes, I agree, that would be better.

**Comment by iHiD** [comment]
Triaged.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
