### ISSUE TITLE
Leave of Absence notification

### ISSUE THREAD

**Issue by jacobsandersen** [exercism/v2-feedback#162]
Greetings,

Please see the Slack thread: https://exercism-mentors.slack.com/archives/CAQP7JL3T/p1529803004000045

Mentors should have the ability to let everybody know they are currently away and not mentoring. Ideally, it should have a "return date" that will show on the profile letting people know when they will be back.

**Comment by iHiD** [comment]
I like it. Will look into it post-launch. Thanks.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
