### ISSUE TITLE
mentorcism: No students everywhere, except the tracks I joined myself

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#164]
When I'm on the tracks overview, I do see elixir and erlang as joined tracks, with 6/4 students participating.

All the languages I have not joined yet, are displayed with 0 participants.

**Comment by iHiD** [comment]
@NobbZ Great catch. 

[This](https://github.com/exercism/prototype/blob/master/app/views/my/tracks/_tracks.html.haml) needs an expiry. It'll get fixed before launch.

**Comment by iHiD** [comment]
Triaged. Thanks.
