### ISSUE TITLE
(in)Consistency between notification banner and submission's "Next Step" Mentor Discussion blurb

### ISSUE THREAD

**Issue by HarrisonMc555** [exercism/v2-feedback#166]
When my first post-helloworld exercise was first "approved" by a mentor, I didn't realize it. When I looked at the submission, the first thing I looked at was for comments from my "mentor". Instead, I saw a blurb saying "...A mentor will check out your work and leave a comment here on your solution soon.".

However, I later noticed that there was a banner _above_ the solution, saying "A mentor has approved this solution".

This seems to me to be inconsistent. I would recommend disabling the "A mentor will check out your work..." blurb once it has been reviewed by a mentor.

This may be a topic for another issue, but I would assume it isn't kosher to "approve" a solution without leaving a message or even a "reaction", would it? I'm not sure if it would be too much to disable "approval" without some sort of interaction...

![exercism-v2_mentor-has-approved](https://user-images.githubusercontent.com/22666187/41821329-23ceddbe-779c-11e8-88aa-1518a9ef72f4.png)

**Comment by iHiD** [comment]
Yeah - that's a state I've not defended for. Thanks.

**Comment by iHiD** [comment]
I've fixed this on master. Thanks.
