### ISSUE TITLE
submissions to lang/exercise only visible if not commited to that lang/exercise so far

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#17]
The track overview for an exercise shows fine when one has not yet submitted a solution for the exercise on that track (https://v2.exercism.io/tracks/$LANG/exercises/$EXERCISE/solutions).

As soon as one submits a solution to that track and exercise the same URL gives an 500.

----

I know, we were not supposed to post about 500s, but we discovered this pretty quickly when trying with 4 persons and created an amount of bugsnaps that might not be related at a first glance. Therefore we decided to post about our discovery including all discovered details

**Comment by kytrinyx** [comment]
Thanks @NobbZ—I'll link to this from our bugsnag channel, as the extra context will likely be helpful.

**Comment by iHiD** [comment]
Fixed. Thanks.
