### ISSUE TITLE
mentorcism: Code is not highlighted in the submitted solution in the common-lisp track

### ISSUE THREAD

**Issue by tushartyagi** [exercism/v2-feedback#170]
When I submit a solution for `Common Lisp` track and open the solutions page on the website as a student or as a mentor, then the code is not highlighted in the `Solution` or in the `Test Suite` tab. 

![image](https://user-images.githubusercontent.com/1630265/41821834-2d3dc62c-7804-11e8-857d-1c61c4cea1c9.png)

**Comment by kytrinyx** [comment]
@iHiD we have common-lisp in the prism languages here:
https://github.com/exercism/prototype/blob/0cc929e548dd2f2e9ab4083f85c4c025ce938dee/config/initializers/prism.rb#L156

Not sure what's going on with this.

**Comment by tushartyagi** [comment]
@kytrinyx @iHiD I'm not too sure how the code works, but while we have lisp in `Exercism::PrismLanguageMappings`, it's not present in `
Exercism::PrismFileMappings` here https://github.com/exercism/prototype/blob/0cc929e548dd2f2e9ab4083f85c4c025ce938dee/config/initializers/prism.rb#L239

How will the highlighter know that a file with extension `.lisp` is supposed to be common lisp?

**Comment by iHiD** [comment]
Thanks. You're right. Feel free to PR for common lisp if you like. I've got an open issue on our internal tracker for all these to be checked before launch.

**Comment by tushartyagi** [comment]
I've raised a PR. Let me know if anything else is required in that code.

**Comment by iHiD** [comment]
Thanks. I'll merge and deploy when I get chance (probably tomorrow evening BST) and then we can see if it's fixed it :)

**Comment by iHiD** [comment]
@tushartyagi I've deployed. Could you validate whether that has helped please?

**Comment by tushartyagi** [comment]
@iHiD That is not working :( 
I hope this is not a cache issue, but I've tried with private tab.

**Comment by tushartyagi** [comment]
So with my non-existing knowledge of Ruby, I found that the function that actually sends details about the language syntax highlighting is [syntax_highlighter_for_filename](https://github.com/exercism/prototype/blob/aa17cdf04edbaa5dd50c21523e8284d2d525933c/app/helpers/file_helper.rb#L9) and it gets populated at [set_prism_languages_for_tracks](https://github.com/exercism/prototype/blob/8659e2d3afd7ae36284871c3c23abb262d1ced01/app/services/set_prism_languages_for_tracks.rb#L9).  

My previous PR was sending `language-common-lisp` instead of `language-lisp` as the html class attribute. 
I've also confirmed in [language list](https://prismjs.com/#languages-list) at prismjs homepage and prism wants `language-lisp` instead of `language-common-lisp`  to enable lisp syntax highlighting.

@iHiD Unless there's some other sorcery involved, it's supposed to work like this. If yes, then I've raised a PR https://github.com/exercism/prototype/pull/77 

Hopefully it should work :crossed_fingers:

**Comment by iHiD** [comment]
@tushartyagi How's this looking now?

**Comment by tushartyagi** [comment]
@iHiD Looking Great! Thanks

![image](https://user-images.githubusercontent.com/1630265/42136594-208feb80-7d7c-11e8-9b61-5c566a51e278.png)

**Comment by iHiD** [comment]
Brilliant. Thanks for your help.
