### ISSUE TITLE
mentorcism: Approving solution does not hide pass button

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#171]
When I approve a solution, the `I'll pass, thanks` button is still displayed. Shouldn't that be hidden after approving?

![image](https://user-images.githubusercontent.com/135246/41845885-52d162f6-7875-11e8-8ca5-0df5c884185e.png)

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
