### ISSUE TITLE
mentorcism: Cannot easily continue to next solution to mentor

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#172]
When I have reviewed a solution, there is no easy way to go to the next solution, except for to go back to the completed list of solutions to review. I think it would help speed up things if there was such a link.

**Comment by carolineschnapp** [comment]
I agree wholeheartedly.

The mentor dashboard UI is quite slow to render too, so going back to it to look at the next submission to mentor is a bit painful.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
