### ISSUE TITLE
Request: Additional exercise states

### ISSUE THREAD

**Issue by melston** [exercism/v2-feedback#175]
This request applies predominately to the 'extra' exercises but it could also apply to the primary track exercises.

It is a bit annoying that the act of downloading an exercise marks it as "In Progress."  The problem is that it makes that exercise indistinguishable from all the other exercises that are also "In Progress."  If I have downloaded an exercise and not submitted a solution yet I can't tell this from the '/my/tracks/<language>' page as all exercises, whether downloaded or submitted (but not yet approved), are shown identically.

For my purposes, a better solution would be to identify all exercises with submitted solutions with a different state.  Perhaps "Submitted" or "Waiting Review", or something similar.  If a solution is submitted but is not accepted (e.g. the mentor believes more should be done) then it could be moved back to the "In Progress" state, indicating (at a glance) which exercises require further work on the student's part.

It might even be helpful for the student to mark a "Completed" solution as back to "In Progress" if s/he wishes to do some further work on it and get more feedback.

**Comment by iHiD** [comment]
Totally agree with this. Very helpful - thank you.

We're realistically not going to get round to it before launch, but I've triaged it as a next priority afterwards.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
