### ISSUE TITLE
500 Internal Server Error when submitting some previous (non-current) exercise

### ISSUE THREAD

**Issue by HarrisonMc555** [exercism/v2-feedback#176]
When I tried to submit a revised version of an exercise (Python: reverse-string), I got a `500 Internal Server Error`. When I made *another* edit and submitted that, it gave me the same error. However, when I edited the current exercise I was on (Python: bob) **and** a completely different exercise (Python: leap), it didn't return an error.

I wish I could provide more details for debugging, but I'm not sure what else to provide. Here's the output of `mentorcism troubleshoot`:

```
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.0-alpha.9.mentors
Latest:  2.4.1


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/harrison
Workspace: /home/harrison/mentorcism
Config:    /home/harrison/.config/mentorcism/user.json
API key:   9f1c*****************************d22

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 88.684484ms

Exercism:
    * https://mentors-beta.exercism.io/api/v1/ping
    * [connected]
    * 671.547354ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
```

**Comment by iHiD** [comment]
I'll assign to this to @kytrinyx. She will probably need some more details on the exact commands you ran. I can't see anything in the logs to help frustratingly. Thanks for reporting :)

**Comment by yeongsheng-tan** [comment]
In my case, I'll always get an HTTP 500 error on first submission (e.g. nucleotide-count #elixir-track, or bob #elm-track). Doing a second submission and it goes through fine.

**Comment by carolineschnapp** [comment]
I am same as @yeongsheng-tan. 

```
➜  difference-of-squares mentorcism > submit difference_of_squares.rb
Error: 500 Internal Server Error
➜  difference-of-squares > mentorcism submit difference_of_squares.rb
➜  difference-of-squares > 
```

The second try is the charm. It works, although no feedback is given in the console.

PS. Some feedback with a link would be amazing, as does V1.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
