### ISSUE TITLE
Notification sends me to wrong iteration of exercise

### ISSUE THREAD

**Issue by HarrisonMc555** [exercism/v2-feedback#177]
I recently got a notification that a mentor had reviewed my exercise. However, when I clicked on the box, it sent me to my most recent iteration, which was not the iteration the mentor had commented on.

Will notifications always send you to the most recent iteration? I'm guessing this is not by design.

**Comment by iHiD** [comment]
> Will notifications always send you to the most recent iteration? I'm guessing this is not by design.

They will at the moment, but you're right that they probably shouldn't! I'll fix this. Thanks.

**Comment by iHiD** [comment]
Triaged. Thanks.
