### ISSUE TITLE
Make it easier to download next core track exercise

### ISSUE THREAD

**Issue by HarrisonMc555** [exercism/v2-feedback#178]
This may be something that can wait until after launch, but I think it would significantly improve the UI.

One thing I liked about exercsim-v1 was that if I wanted to download the next exercise, I simply typed `exercism download <track>`. I didn't even have to open a browser or anything.

This may be by design in order to encourage people to actively check the exercism-v2 page and see the feedback they've gotten before downloading the next exercise. I'm guessing that's why you have to manually "complete" an exercise in order to move on to the next one.

Maybe I'm just lazy, but it just seems a little annoying to go to the next core exercise's page, copy and paste the download command or exercise slug, go back to my command line, and download it.

**Comment by iHiD** [comment]
> One thing I liked about exercsim-v1 was that if I wanted to download the next exercise, I simply typed exercism download <track>. 

I'm not convinced that was the case for v1. How would it know which exercise to download?

I have mixed feelings about this. I wouldn't be against something like `exercism download --current-core` or something, but as you'll already be in the UI to unlock the next core exercise anyway, I think the one extra click into the exercise and then the copy/paste click is probably not really much harder than typing the command in the terminal.

I'll mark this as a feature request and I'm happy to discuss it more once we've launched. I'm sure @kytrinyx will have thoughts too :)

**Comment by peschkaj** [comment]
In exercism v1 it was possible to type `exercism f haskell` (for example). 

You mention "but as you'll already be in the UI to unlock the next core exercise anyway, I think the one extra click into the exercise and then the copy/paste click is probably not really much harder than typing the command in the terminal." 

In my case, my workflow didn't involve the web UI. I would almost always fetch another exercise and start thinking about it while I was still in a problem solving mode. For many shells, it's possible to start typing a command and then cycle through all past commands that begin with whatever you've typed. For exercism, I could type `exer` and then press up once or twice and I would be ad `exercism f CURRENT_TRACK`.

In this case, it's not that this is an enhancement or new feature request, it's that a core workflow feature was removed.

**Comment by NobbZ** [comment]
Besides the exercises from the core track, there is no order anymore, so fetching the “next” exercise isn't possible ;)

Also, when you submitted a solution for the nth exexercise on the core a command like the old `fetch` would gain you nothing, as the n+1th exercise hasn't been unlocked yet. You need to wait for mentor-approval and finalizing the exercise. This happens on the web page only.

**Comment by peschkaj** [comment]
Thanks for the clarification @NobbZ.

it sounds like there's a much clearer workflow and focus on mentoring new developers, whereas I was looking for language practice over a track of guided exercises.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
