### ISSUE TITLE
choosen aliases in privacy settings might get other people into trouble

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#18]
In the privacy settings one can choose an alias per track. One can abuse this feature to offense other people:

![alias-attack](https://user-images.githubusercontent.com/58951/29480889-276333d0-847c-11e7-9cc2-efa455e4437f.png)

The avatar-less `kotp` has created the name with a tool which is online available and easily googable, therefore I won't into details. It is composed from unicode letters that look close to the letters of the originals.

This fake-kotp can now submit comments which do not comply to the code of conduct. Even though the administrator team can delete those and ban the pseudonomised user, other users that have seen this comment will remember it as beeing written by kotp, which at the end harms his reputation.

Therefore aliases should be generated by the system instead of freely choosen.

**Comment by kytrinyx** [comment]
I agree that we should not allow incidental harassment as you describe. This is a well-known attack vector, and we certainly need to make sure that we address it.

I'm opening an issue in our product/ux tracker so that we can address this.

Thanks!

**Comment by kytrinyx** [comment]
@NobbZ after having discussed this with the product team, we've decided to restrict aliases and usernames to alphanumeric + hyphens.

This ensures that we do not get look-alike names, while also giving people the freedom to choose their own aliases.

This is being deployed now.
