### ISSUE TITLE
[mentorcism] Comment preview doesn't handle paragraphs

### ISSUE THREAD

**Issue by JoelQ** [exercism/v2-feedback#182]
![exercism 2018-06-26 23-59-13](https://user-images.githubusercontent.com/1006966/41952289-3408a1a8-799d-11e8-8777-b81d60893527.jpg)

![exercism 2018-06-27 00-01-49](https://user-images.githubusercontent.com/1006966/41952325-4df35220-799d-11e8-8d50-fb9bc5b218f5.jpg)

![exercism 2018-06-27 00-02-39](https://user-images.githubusercontent.com/1006966/41952352-6e4dd9f0-799d-11e8-90b9-52f73f320455.jpg)

**Comment by iHiD** [comment]
Thanks. Triaged as a bug.

**Comment by iHiD** [comment]
Closing in favour of https://github.com/exercism/exercism.io/issues/3884 (to avoid duplicate during our merging of issues)

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
