### ISSUE TITLE
[mentorcism] Author comments do not appear after clicking submit

### ISSUE THREAD

**Issue by JoelQ** [exercism/v2-feedback#184]
When responding to mentor feedback on this exercise https://mentors-beta.exercism.io/my/solutions/6f94eb5e8d134b37ba74b629e5602269, I clicked the "submit" button and  nothing seemed to happen. The comment box didn't clear out, the comment didn't appear in the feed. I clicked a couple more times still nothing.

Figuring this might be a UI bug, I refreshed the page and then saw my comment show up three times.

**Comment by iHiD** [comment]
Thanks for reporting. I'm going to mark this as a duplicate of #184
