### ISSUE TITLE
Ability to stay on the current solution page when clicking on complete

### ISSUE THREAD

**Issue by MarcosX** [exercism/v2-feedback#186]
![screen shot 2018-06-27 at 07 13 46](https://user-images.githubusercontent.com/856376/41987033-6d4e59dc-7a0e-11e8-989a-86aa8a97403f.png)

As shown in this screenshot, once someone clicks on complete exercise there is really no flow other than going to the next track.

Usually that's the normal flow and not having the option to close that modal works fine, but I happened to click on the complete button by mistake and had no other way to stay on the page.

**Comment by iHiD** [comment]
@MarcosX Makes sense. We'll have a think about this after we've launched. Thanks :)

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
