### ISSUE TITLE
[mentorcism] request -- Add ability to edit mentor comments

### ISSUE THREAD

**Issue by aldraco** [exercism/v2-feedback#188]
Having another opportunity to edit comments that you have made to clarify what you mean could be helpful. Sometimes you just need another chance after hitting submit and realizing you weren't very clear about something.

I understand how this could also be a vector for harassment, but it would be a nice feature to have.

**Comment by iHiD** [comment]
Triaged. Thanks.

**Comment by carolineschnapp** [comment]
Maybe we could have like a 1-hour window or even less to edit our own comments.

**Comment by NobbZ** [comment]
In my opinion, if editing is enabled (which would me happy), it should definitively have a full editing history, visible for everyone (who can read the conversation).

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
