### ISSUE TITLE
[Mentors Dashboard] When non-default status is selected returning back to the dashboard discards the selected option

### ISSUE THREAD

**Issue by oliakremmyda** [exercism/v2-feedback#189]
When non-default status is selected leaving the dashboard and returning back does not remember the selected option

I have noticed that when you are in 
the _mentors dashboard > Select status: `Waiting for them` > Open one solution > use back button_ 
to check the rest waiting solutions and they are disappeared. 
You have to choose another status and then back the _waiting_ one to see them again

**Comment by iHiD** [comment]
Triaged. Thanks.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
