### ISSUE TITLE
Unanticipated payload on "download" of Hello-World, Delphi track

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-feedback#19]
@rpottsoh commented on [Fri Aug 18 2017](https://github.com/exercism/cli/issues/467)

Feel free to edit the title if this issue relates to more than the Delphi track.

This is what I ended up with upon invoking
```example
C:\Nextercism\delphi>nextercism download hello-world
```

```example
C:\Nextercism\delphi>nextercism download hello-world

Downloaded to
c:\nextercism\delphi\hello-world

C:\Nextercism\delphi>dir
 Volume in drive C is OS
 Volume Serial Number is 3E0E-CBF1

 Directory of C:\Nextercism\delphi

08/18/2017  05:44 PM    <DIR>          .
08/18/2017  05:44 PM    <DIR>          ..
08/18/2017  05:44 PM    <DIR>          hello-world
               0 File(s)              0 bytes
               3 Dir(s)  24,409,522,176 bytes free

C:\Nextercism\delphi>cd hello-world

C:\Nextercism\delphi\hello-world>dir
 Volume in drive C is OS
 Volume Serial Number is 3E0E-CBF1

 Directory of C:\Nextercism\delphi\hello-world

08/18/2017  05:44 PM    <DIR>          .
08/18/2017  05:44 PM    <DIR>          ..
08/18/2017  05:44 PM             1,637 HelloWorld.dpr
08/18/2017  05:44 PM    <DIR>          lib
08/18/2017  05:44 PM             2,027 README.md
08/18/2017  05:44 PM             2,495 uTestHelloWorld.pas
               3 File(s)          6,159 bytes
               3 Dir(s)  24,409,522,176 bytes free

C:\Nextercism\delphi\hello-world>cd lib

C:\Nextercism\delphi\hello-world\lib>dir
 Volume in drive C is OS
 Volume Serial Number is 3E0E-CBF1

 Directory of C:\Nextercism\delphi\hello-world\lib

08/18/2017  05:44 PM    <DIR>          .
08/18/2017  05:44 PM    <DIR>          ..
08/18/2017  05:44 PM                 0 three.py
               1 File(s)              0 bytes
               2 Dir(s)  24,409,522,176 bytes free

C:\Nextercism\delphi\hello-world\lib>
```

I am not expecting a `lib` folder or any zero length python files.

---

@kytrinyx commented on [Fri Aug 18 2017](https://github.com/exercism/cli/issues/467#issuecomment-323490525)

Thanks @rpottsoh! Would you mind opening this on the v2-feedback repo? I don't yet know if this problem is in CLI or the API, and I want to track everything nextercism-related over there.

**Comment by kytrinyx** [comment]
This is the oddest thing!

Here's what I got when I downloaded the delphi hello-world:

```
$ tree -a delphi/
delphi/
└── hello-world
    ├── .solution.json
    ├── HelloWorld.dpr
    ├── README.md
    └── uTestHelloWorld.pas
```

Which all looks perfectly correct to me.

When I do a curl command to call the endpoint I get this (redacted)

```
$ curl -XGET -v -H "Authorization: Bearer REDACTED" "https://api.exercism.io/v1/solutions/latest?track_id=delphi&exercise_id=hello-world"
*   Trying 52.210.116.236...
* Connected to api.exercism.io (52.210.116.236) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: exercism.io
* Server certificate: Amazon
* Server certificate: Amazon Root CA 1
* Server certificate: Starfield Services Root Certificate Authority - G2
> GET /v1/solutions/latest?track_id=delphi&exercise_id=hello-world HTTP/1.1
> Host: api.exercism.io
> User-Agent: curl/7.43.0
> Accept: */*
> Authorization: Bearer REDACTED
> 
< HTTP/1.1 200 OK
< Cache-Control: max-age=0, private, must-revalidate
< Cache-control: no-cache="set-cookie"
< Content-Type: application/json; charset=utf-8
< Date: Sat, 19 Aug 2017 04:30:30 GMT
< ETag: W/"26a9eb13cb2c57573c4b46ac48375bf8"
< Server: nginx/1.10.3 (Ubuntu)
< Set-Cookie: _exercism_session=REDACTED; path=/; HttpOnly
< Set-Cookie: AWSELB=REDACTED;PATH=/
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-Request-Id: 2afabf64-be1d-4574-8124-1e34be32c0e5
< X-Runtime: 0.049755
< X-XSS-Protection: 1; mode=block
< Content-Length: 551
< Connection: keep-alive
< 
* Connection #0 to host api.exercism.io left intact
{"solution":{"id":"ce0855cf-d3af-4178-af68-5e2d2ae4dbca","url":"https://v2.exercism.io/my/solutions/ce0855cf-d3af-4178-af68-5e2d2ae4dbca","user":{"handle":"kytrinyx","is_requester":true},"exercise":{"id":"hello-world","instructions_url":"https://v2.exercism.io/my/solutions/ce0855cf-d3af-4178-af68-5e2d2ae4dbca","track":{"id":"delphi","language":"Delphi Pascal"}},"file_download_base_url":"https://api.exercism.io/v1/solutions/ce0855cf-d3af-4178-af68-5e2d2ae4dbca/files/","files":["HelloWorld.dpr","README.md","uTestHelloWorld.pas"],"iteration":null}}
```

The API response looks correct to me. There is no reference here to any `lib` directory or stray (zero-length) Python files.

Clearly there is something I'm missing!

**Comment by rpottsoh** [comment]
`.solution.json` is a hidden file in Windows.  Intentional?

**Comment by kytrinyx** [comment]
@rpottsoh Yepp, it's hidden on all platforms. I didn't bother changing the name for Windows, even though starting with a `.` is unconventional.

I can't find anything referencing this `lib` and `three.py` within the client, but I know that I did some testing with some fixtures named like this when we first started testing out uploads and downloads to the v2 API.

~~I have a suspicion that these files were not wiped when we wiped our data, and that your exercise got the same ID as my previous one.~~

~~ccare would you take a look at the stored files for solution uuid 7db13669-6356-413d-a334-3ab422ead6ed and see if you can see some trace of some of our early test data?~~

UPDATE: these are files that got created when clicking the "create fake submission".

**Comment by rpottsoh** [comment]
The problem is repeatable.  I just removed my hello-world folder and performed another download, got the same exact result as the first time.

The hidden file was a minor surprise.  If one is working the folder via Windows Explorer it is no big deal, it will delete the folder whether folder is empty or not if you want to delete it.  If one is trying to remove the folder via cmd they will be informed that the folder is not empty if they have done a `del *.*` to remove the contents prior to a `rd hello-world`....  A savvy person will figure this out that there is something hidden in the folder.  Does the file really need to be hidden?

**Comment by kytrinyx** [comment]
> Does the file really need to be hidden?

I don't know that it _needs_ to be hidden, but I would rather not that people who are just solving exercises see it, because it's likely to confuse them more than not.

It's a good question, though.

**Comment by ErikSchierboom** [comment]
@kytrinyx I also see (two) `lib/three.py` files in a C# submission: https://v2.exercism.io/mentor/solutions/8a3e0326-cd84-499f-9485-cdc1f5d81da7

**Comment by iHiD** [comment]
@ErikSchierboom The `lib/three.py` are the files that are automatically created when you click the "Create fake submission" button, so this is (weirdly) intentional, rather than a bug.

**Comment by NobbZ** [comment]
@iHiD can't you create them with content? "I'm a fake submission" or similar, also it feels odd, that there are 2 distinct files listed with the same name and path…

**Comment by kytrinyx** [comment]
I had never used the "create fake submission", so was unaware that one of my earliest fixtures ended up there.

I think we should make the following change:

Rename the file to be something like `fake-submission-created-with-button.txt`, and the contents "Fake content".

**Comment by iHiD** [comment]
Clicking the button and then submitting via the CLI is not an expected behaviour. You can use the CLI to submit a proper solution, or you can click the button to create a fake solution if you just want to test out bits of the UI and don't want to use the CLI for now. The button is only there to allow you to progress quickly. Clicking it is effectively skipping the CLI part of this. 

@kytrinyx I have updated it as you suggested and changed it to one file. I'll deploy shortly.

**Comment by kytrinyx** [comment]
Just tried this out and it is much easier to understand. Thanks @iHiD

**Comment by iHiD** [comment]
Thanks everyone. I didn't really think this bit through - it was more of a step just to help us test things before the CLI was in place. We'll probably get rid of it altogether as the next part of the beta once all the CLI are bugs are ironed out in the next week or so.
