### ISSUE TITLE
[mentorcism] Solutions you've liked: color of count indicators perhaps inconsistent

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-feedback#191]
![image](https://user-images.githubusercontent.com/6978003/42095559-f3e63442-7b80-11e8-8035-f06a59c17609.png)

Shouldn't the :heart:  also be grey as the total is zero?  Shouldn't :+1: be some other color than grey since it has a total greater than zero?

**Comment by iHiD** [comment]
Triaged. Thanks.
