### ISSUE TITLE
Add a few emojis on mentors comments

### ISSUE THREAD

**Issue by oliakremmyda** [exercism/v2-feedback#193]
I thing it would be a nice add on if mentor comments could include a 👍 icon or a 😄 to react on a solution, for a more positive feedback!

**Comment by iHiD** [comment]
That's a great idea.

**Comment by scarerkite** [comment]
I would really like this too!

I've had a couple of instances where I've given a very small note (e.g. a typo or something) after the solution was approved, the student has uploaded a new iteration and as far as I can tell, the only way to remove it from 'Action required' on my dashboard is to comment on it.
For those kinds of things, I would love to be able to give a 👍to acknowledge it, without needing to write a comment.

**Comment by iHiD** [comment]
We'll definitely do this.

In the interm period before we do so, you *should* be able to copy and paste emojis in from somewhere like Slack. I know this is entirely suboptimal, but just in case you every **really** want to use one, that should work :)

**Comment by n8chz** [comment]
Perhaps the system can award the ⛳ emoji to the smallest source that passes the tests.

A "Conway game of life" emoji should be awarded to hacker-level iterations, but for some reason it doesn't seem to be in Unicode, bizarre considering it's both graphically simple, iconic, and has been around awhile.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
