### ISSUE TITLE
diffs for mentors

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#196]
As a mentor, I'd like to see a diff between the curent and a previous iteration. probably even along with the comments given on the older submission.

**Comment by iHiD** [comment]
Nice. Agree. Will tag as feature-request for us to consider as we move forward.

**Comment by carolineschnapp** [comment]
I believe the old exercism had a “diff” feature to compare iterations, and also had a copy to clipboard button.

The copy to clipboard is helpful to copy the student code locally, to run the tests on.

**Comment by NobbZ** [comment]
The `exercism d --uuid` is much better than a copy to clipboard, as it downloads the correct tests as well. At least for those submitted with >= 3.0 clients.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
