### ISSUE TITLE
mentorcism: Code is not highlighted in the submitted solution in the Clojure track

### ISSUE THREAD

**Issue by jgomo3** [exercism/v2-feedback#197]
![image](https://user-images.githubusercontent.com/1125678/42356249-0f681ae8-80ac-11e8-974a-3ba3234db34d.png)

The solution URL is: https://mentors-beta.exercism.io/my/solutions/4e3c93e69fc84cf38ccdde2603f9f537

jgomo is my user.

**Comment by iHiD** [comment]
@jgomo3 Thanks for reporting. Do you fancy doing a PR for this to prototype, similar to [this one](https://github.com/exercism/prototype/pull/75). If you don't have time, I'll try and get round to it before launch. Thank you :)

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
