### ISSUE TITLE
mentorcism: "Problem" Avatar missing in some problems

### ISSUE THREAD

**Issue by jgomo3** [exercism/v2-feedback#198]
I.e, The Armstrong Numbers in the Clojure Track is rendered like this:

![image](https://user-images.githubusercontent.com/1125678/42356306-58866234-80ac-11e8-9425-b057a8eb4777.png)

**Comment by iHiD** [comment]
@jgomo3 Closing this as a duplicate of #153 but very much appreciate you reporting it. Thanks :)
