### ISSUE TITLE
Unable to submit csharp solution to "leap" exercise

### ISSUE THREAD

**Issue by pdmoore** [exercism/v2-feedback#199]
When I try to submit a solution to the leap exercise nothing is submitted. I issue the command "mentorcism submit leap" from the directory where the mentorcism.exe file is. That command generates a list of files to be submitted and prompts me to ENTER, which I do. After hitting enter I see this warning and then nothing:

`Press ENTER to submit, or control + c to cancel:
Submitting files now...Warning: file C:\pdm\Code\mentorcism\csharp\leap\.vs\Leap\v15\Server\sqlite3\db.lock was empty, skipping...
C:\pdm\Code\mentorcism>`

This same submission process did work for the hello-world exercise on the csharp track. That submission did upload the 20+ files as has been reported in issue https://github.com/exercism/v2-feedback/issues/48

**Comment by iHiD** [comment]
@pdmoore Thanks. I've triaged this to @kytrinyx on our internal tracking list.

**Comment by kytrinyx** [comment]
I've done a bunch of work on the submit command in the past couple of days. I'm going to cut a proper release, and I'll post back here so you can try it.

**Comment by kytrinyx** [comment]
Ok! Sorry for the delay, the latest client is up on https://github.com/exercism/cli/releases/latest

Would you take a look to see if it fixes the issue?

**Comment by pdmoore** [comment]
Will do as soon as I get home. Hoping it's a one-off with my Win10 machine
as I'm seeing a lot of solutions coming through on the C# track.

**Comment by pdmoore** [comment]
Yes! Am able to submit Csharp solutions now with the latest CLI.

Thanks,
-paul

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
