### ISSUE TITLE
Complete Exercise button stays clickable when going back to a completed exercise

### ISSUE THREAD

**Issue by corroded** [exercism/v2-feedback#200]
In my exercise here https://mentors-beta.exercism.io/my/solutions/4da16becb7e1473eaa08d7f9074bfb5b?iteration_idx=3, I have already pressed `Complete Exercise` and have seen the rate your mentors modal. After going through that, I refreshed the page and could still click the `Complete exercise` button - and rate my mentors again additionally.

Not sure if it actually spams reviews in the backend but the UI should at least hide/disable the button if the exercise has already been completed. I should still be able to comment though (to thank my mentors).

![image](https://user-images.githubusercontent.com/46548/42426154-4b283fb4-8358-11e8-9059-509942dbbea5.png)

See the screenshot above. It says `Well done! Your solution is completed.` but the `Complete Exercise` button remains clickable.

**Comment by iHiD** [comment]
Thanks for reporting. I've just put a PR for this in.
