### ISSUE TITLE
mentorcism: Exercises unlocked page doesn't make main exercise clickable

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#201]
When I completed my hello-world submission on the Kotlin track, I got this pop-up:

![image](https://user-images.githubusercontent.com/135246/42432931-4e99013e-834d-11e8-995f-73500086f9fe.png)

I then tried to click on the main, showcased exercise (Two Fer) to go the exercise's page and copy the download command. Unfortunately couldn't click on it. However, I could click on the other exercises, with the smaller icons. I think it would make sense to also have the main exercise be clickable.

**Comment by iHiD** [comment]
Nice suggestion. PR submitted. Thanks :)

**Comment by ErikSchierboom** [comment]
Nice!
