### ISSUE TITLE
mentorcism: student glyph not always appearing in "Your Notifications"

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-feedback#202]
If what I am about to describe has already been raised in another issue, I apologize in advance for my redundancy.

In My Notifications window  (that I get to by clicking the bell icon towards the upper right corner) today I was presented with:

![image](https://user-images.githubusercontent.com/6978003/42453396-99e03ec0-835a-11e8-9cf9-aff5cd04700d.png)

Notice that I have three posts from the same student.  However, the third is lacking the student's glyph.  An odd behavior that should be brought to your attention.

This is the only time I have come across this occurrence.

**Comment by iHiD** [comment]
@rpottsoh Can you reproduce this still? If so, could you send me the html source of the page pls?

**Comment by rpottsoh** [comment]
Not sure if I can reproduce.  Will try.  @amoradell please submit three exercises for me to mentor; to see if we can reproduce this issue.

**Comment by amoradell** [comment]
I submitted several exercises this evening. Sorry for the delay. Coupe du monde oblige...

**Comment by rpottsoh** [comment]
I'll check it out, thanks. ⚽️

**Comment by rpottsoh** [comment]
@iHiD The problem has repeated itself.  Here is the html source.

[view-source_https___mentors-beta.exercism.io_my_notifications.zip](https://github.com/exercism/v2-feedback/files/2190323/view-source_https___mentors-beta.exercism.io_my_notifications.zip)

Looks like:
![image](https://user-images.githubusercontent.com/6978003/42659504-76449f94-85f6-11e8-8bb8-91d29d7fa1c8.png)

**Comment by iHiD** [comment]
Super-helpful thanks. Fixed on master :)
