### ISSUE TITLE
mentorcism: Links in header of solution page don't work as expected

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#204]
If I view a specific solution, e.g. by going to [this page](https://mentors-beta.exercism.io/tracks/kotlin/exercises/hamming/solutions/2bc5d352d9294e5e9dfcaee48162198d), there are two links below the `"<username>'s solution` header: one for the exercise and for the track:

![image](https://user-images.githubusercontent.com/135246/42568135-61f5dcd2-850c-11e8-9412-0490ff1255e2.png)

The exercise link leads me to the track page, and the track link leads me to the current solution. I think that the link behind the exercise link should actually be the track's link. I'm not sure what the solution link should be.

**Comment by iHiD** [comment]
@ErikSchierboom So the track link is broken (I've submitted a PR), but the exercise link seems to be right for me. What's the URL you end up on after you click it?

**Comment by ErikSchierboom** [comment]
@iHiD Well, the link looks correct, https://mentors-beta.exercism.io/tracks/kotlin/exercises/hamming, but clicking on it then redirects to https://mentors-beta.exercism.io/my/tracks/kotlin.

**Comment by iHiD** [comment]
OK - cool. Thanks. It doesn't redirect me. I'll have a look :)

**Comment by iHiD** [comment]
PR submitted. Thanks :)

**Comment by ErikSchierboom** [comment]
Great!
