### ISSUE TITLE
mentorcism: Cannot clear star rating

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#205]
When one completes an exercise, you can give stars to rate your mentor:

![image](https://user-images.githubusercontent.com/135246/42570128-2918d3e0-8513-11e8-8c34-2605004de167.png)

However, once you select one or more stars, you cannot then unselect the stars.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
