### ISSUE TITLE
rust: "twofer" showing in core track, but cannot download

### ISSUE THREAD

**Issue by yawpitch** [exercism/v2-feedback#206]
I'm in the rust track and the second item in the core exercises displayed for me is "Twofer" ... there is no problem introduction beyond the title "Introduction", and any attempt do download the exercise with mentorcism throws:

```Error: unable to parse API response - invalid character '<' looking for beginning of value```

It appears that at some point "two-fer" was [deprecated](https://github.com/exercism/rust/commit/c1c6dab10729db4a0ef57b22882c38f3bd5f3df3) and [renamed](https://github.com/exercism/rust/commit/e7fb51026912753414601d8dd1c5fafb15683216) "twofer" ... but neither appears to be part of the core track for Rust.

Thread on Slack [here](https://exercism-mentors.slack.com/archives/CAQP7JL3T/p1531337261000171).

**Comment by iHiD** [comment]
@yawpitch Thanks for reporting. This was noted in https://github.com/exercism/rust/issues/564 and is fixed in the beta site but not yet on the mentors-beta site.

**Comment by yawpitch** [comment]
@iHiD that's fine, closing this one.
