### ISSUE TITLE
Running the website on windows

### ISSUE THREAD

**Issue by FabienTregan** [exercism/v2-feedback#209]
Hi, I tryed to run the server on windows following the instructions in https://github.com/exercism/website/blob/master/README.md and needed to add a few step (I know some of them are windows related, not sure they all are.)

* before installing Ruby, I needed to install CMake
* add this line to gemfile : `gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]` (unwanted on linux)
* before running any of the `bundle` commands, I hade to install bundle : `gem install bundler`
* after the mysql commands, I hade to `mysql -e "ALTER USER 'exercism_reboot'@'localhost' IDENTIFIED WITH mysql_native_password BY 'exercism_reboot'" -u root -p`, maybe I was missing a lib to use the default authentification method (that seemed a better solution but I don't know anything about ruby / rails)
* `bundle exec rake bin/setup`did not create the tables, `bin/setup` gives and error. I hadet to `rake db:drop db:create db:schema:load`

then `http://localhost:3000` complains about missing `//= require simplemde/dist/simplemde.min.js`. I could manual fix the problem in an hugly way, but then another .js was unfound. Ihid on slack told me :
>The bin/setup *should* have ran "yarn install" which should have installed the assets. You shouldn't need to add it to the gemfile. [...]

Maybe the problem is that I don't have yarn installed.

I'm not in a hurry to run the server locally, but wanted to trace my experience while am still uneperienced.

**Comment by iHiD** [comment]
@FabienTregan Thanks so much for documenting your steps.

> bin/setup gives and error

Could you tell me what error this gives pls?

**Comment by FabienTregan** [comment]
From a git bash :
```
$ ./bin/setup
The Gemfile's dependencies are satisfied

== Command ["bin/rails db:setup"] failed ==
== Installing dependencies ==

== Preparing database ==
```

**Comment by FabienTregan** [comment]
Update : after deleting / recreating the tables, installing yarn and restarting bin/setup, It now creates the tables but still fails at finding the selectize.js script :

```
$ bin/setup
The Gemfile's dependencies are satisfied

== Command ["bin/rails db:setup"] failed ==
== Installing dependencies ==

== Preparing database ==

Fabien@[...]/nextercism/website (master)
$ bin/rails db:setup
[...]
-- create_table("exercise_topics", {:options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci", :force=>:cascade})
   -> 0.0618s
-- create_table("exercises", {:options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci", :force=>:cascade})
   -> 0.0662s
-- create_table("friendly_id_slugs", {:options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci", :force=>:cascade})
   -> 0.0820s
-- create_table("ignored_solution_mentorships", {:options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci", :force=>:cascade})rails aborted!
ActionView::Template::Error: couldn't find file 'selectize/dist/js/standalone/selectize.js' with type 'application/javascript'
Checked in these paths:
```

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
