### ISSUE TITLE
Please don't close here after moving to non public trackers

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#21]
Closing issues here makes them disappear from the list. And people that discover some issues will probably not look at closed ones since the issue is actually there. 

Please keep issues open here to keep them discoverable and avoid multi reports.

**Comment by Insti** [comment]
Maybe add an 'acknowledged' label or similar to the issue?

**Comment by kytrinyx** [comment]
Ok, thanks.

**Comment by kytrinyx** [comment]
I've reopened the issues.
