### ISSUE TITLE
Solutions you've liked page

### ISSUE THREAD

**Issue by kotp** [exercism/v2-feedback#210]
The page does not show which track or exercise you have liked, nor the iteration that you have marked.

![solutions_you_like](https://user-images.githubusercontent.com/16747/42636222-36e2b0a6-85b6-11e8-9d07-bc13dba8e9b2.png)

**Comment by rpottsoh** [comment]
I think @ErikSchierboom raised the same or similar issue a while back.  I'm not sure of the issue # at the moment.  I'm not at a computer to look.

**Comment by ErikSchierboom** [comment]
@rpottsoh Is correct. See #98.

**Comment by iHiD** [comment]
It's still on out TODO list. Closing in favour of #98. Thanks for reporting though :)

**Comment by kotp** [comment]
I searched for exactly "Solutions you've liked" and did not see that... thanks for knowing it was there @iHiD
