### ISSUE TITLE
Number of mentors of track is incorrect

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#211]
For the C# track, it states that there is one mentor:

![image](https://user-images.githubusercontent.com/135246/42706319-9b55112a-86d6-11e8-89ca-808bbc804505.png)

However, clicking on the mentors shows more mentors: https://exercism.io/tracks/csharp/mentors

**Comment by rpottsoh** [comment]
I would like to echo similar findings on the Delphi track.  I am the only one listed as a mentor, @amoradell should also be listed I believe.   Are they not listed maybe because they have not logged into the new site?.....

**Comment by jpreese** [comment]
Just wanted to pop in and confirm this. @Nobbz also reported this for Erlang.

**Comment by NobbZ** [comment]
Erlang track now claims 3 mentors after I joined, but only 2 are displayed, none of them is in the slack-channel.

Before I joined, the link claimed 0 mentors but displayed the very same two pictures it is displaying now.

**Comment by NobbZ** [comment]
Okay took a closer look, both are in the slack, but have not been active during testing. I do not know if they were active with actual mentoring on the site though.

**Comment by kytrinyx** [comment]
These are taken from two different sources:

- on the track page, we list out the people who have actually joined the mentor track using the configuration link we shared in Slack
- on the mentors page, we list out the people who have submitted bios

**Comment by kytrinyx** [comment]
Chatted with @iHiD -- we're going to standardize on using the count from the mentor bios.

Thanks for bringing it up!

**Comment by amoradell** [comment]
I went to mentoring site several times and got google forms each time

I was mentor on beta

How to become on new site ?

**Comment by NobbZ** [comment]
Come into the slack and read what's posted in #start-here, especially the last 2 steps are important (one contains an URL I do not want to write publicly as anyone who knows it can become mentor everywhere).

**Comment by amoradell** [comment]
It's ok

Thanks
