### ISSUE TITLE
User reflections cannot be edited

### ISSUE THREAD

**Issue by carolineschnapp** [exercism/v2-feedback#213]
User reflections cannot be edited. I found a way which is hackish:

1. Copy your old reflection to the clipboard
2. Go to the track, locate your exercise
3. Click the "Complete Exercise (Unapproved)" button, always clickable even when your solution was already completed. 
4. Paste your reflection, and edit it.

In other words, it's possible to complete an already completed exercise, then you get another chance at submitting a User reflection.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
