### ISSUE TITLE
Filtering doesn't seem to be working properly

### ISSUE THREAD

**Issue by scarerkite** [exercism/v2-feedback#215]
N.B. I'm updating this original post, with updates after the feedback below to try to make things clearer - feel free to close if this is too confusing now!

I'm experiencing a few issues with filtering on the mentor dashboard (for the Ruby track): 

- I just opened the [top solution](https://exercism.io/mentor/solutions/5d641674b8a647b3a7f77d4d99f84290), ~with the filter set to 'Requires action from you'~ in 'Next solutions to mentor' - however there was only one iteration, and another mentor had already commented on it. I would expect only to see an iteration that didn't have a comment on it yet.
- ~When I filter by 'Waiting for them', I would expect to see the solutions that I have commented on. I've commented on 5 so far, but am getting 'You have no solutions in this category.'~ <-- this already covered in https://github.com/exercism/exercism.io/issues/3846 as they were actually in the 'Stale' filter.

The last point was mentioned in https://github.com/exercism/v2-feedback/issues/195 but I'm not sure whether this should be reported separately as it's a slightly different issue to the one originally reported there (apologies for the duplication if not).

**Comment by NobbZ** [comment]
Please check if the solution you expect in waiting for them is in stale instead, please see also exercism/exercism.io#3846.

Also, requires action from you includes solutions you mentored without approving and the student then replied. Are you sure you found your solution there? And not accidentally clicked the first on from next to mentor? There it may happen that there are comments from premigration or other mentors (but the latter shouldn't happen though but @kytrynix confirmed in slack that's there some bug...)

**Comment by scarerkite** [comment]
@NobbZ Yes, you are completely right - because I didn't have any solutions in 'Requires action from you', I was indeed picking up the next solution in 'Next to mentor'.

Also, the ones I expected to see in 'Waiting for them' were indeed in 'Stale' - I hadn't thought to look there.

However, I still would not expect to see a solution in 'Next to mentor', that already has a comment on from another Mentor.
I'll try to update my original comment to reflect this.

**Comment by kytrinyx** [comment]
_Closing. Imported to the https://github.com/exercism/exercism.io repository._
