### ISSUE TITLE
Syntax highlight of java generics and lambdas

### ISSUE THREAD

**Issue by FabienTregan** [exercism/v2-feedback#217]
When inserting some java with generic code, selecting the code then pressing the "code" button, things go fine avec the code syntex highlighted.

But then when you go on the preview tabpane, it get all messed up :
```
private Function<String[], String> x = null;
```
becomes
```
private Function<string string> x = null;
</string>
```
(coma is lost, `String` is lowercased)

and 
```
private Function<String[], List<String>> x = x -> x;
```
becomes
```
private Function<string list>&gt; x = x -&gt; x;
</string>
```

The preview (worst) version is the one that gets in the comment. (Happened to me [here](https://exercism.io/mentor/solutions/564b228764cc4d0b89cfd1bbb1ca5be6#discussion-post-133739))

**Comment by iHiD** [comment]
Could you raise an issue on Prism for this pls: https://github.com/PrismJS/prism/issues

**Comment by NobbZ** [comment]
Are you sure this is prism related and not our markdown renderer?

**Comment by FabienTregan** [comment]
I made a quick test with latest version of prism. The output is less wrong than what we get, but still incorrect.

I am opening an issue on prism, but before it is corrected, some mentors may send comments with unreadable code without noticing (we do not enforece pressing preview before sending the comment, but even then people tend to press prview without atually reading the preview :) ) So this is still an issue on our side.

**Comment by FabienTregan** [comment]
This piece os code is displayed correctly by prism :
```
<pre><code class="language-java">
	private Function&lt;String[], List&ltString>> x = x -> x;
</code></pre>
```
(you have to html escape the `<`s)

**Comment by FabienTregan** [comment]
when you click the "preview" tab, `exercism.io/parse` is called with parameter `markdown:private+Function<String[],+List<String>>+x+=+x+->+x;+`
, the response body is :
```
private Function<string list>&gt; x = x -&gt; x; 
</string>
```
The problems seems to be on the server side. I'm still not able to run the server on my (windows) computer to digg this.

**Comment by kytrinyx** [comment]
_Closing. Imported to the https://github.com/exercism/exercism.io repository._

**Comment by kytrinyx** [comment]
_Closing. Imported to the https://github.com/exercism/exercism.io repository._
