### ISSUE TITLE
Add link to "How Exercism works" section on front page

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#22]
There are links to the "Sign up" page and the "Explore languages" section that you see when viewing the front page, but I would also like to see a link to the "How Exercism works" section, which I find really important as I think it explains what Exercism is about very well, which I assume is what most new people want to know. In fact, I feel that section is more important than the "Explore languages" section.

**Comment by kytrinyx** [comment]
Ah, yes! I think we linked to the "explore languages" because our data suggests that almost everyone goes straight to the languages on the current site, but we really do want people to go to the "how exercism works" section.

**Comment by iHiD** [comment]
@ErikSchierboom Good idea. We've chatted about this and the approach we're going to take is to watch back Hotjar recordings (that watch how people use the site) and see if people scroll down to that. If they don't then, we'll add a link. If they do, then we probably don't need to. I'll leave this open as a reminder.

**Comment by ErikSchierboom** [comment]
Excellent.

**Comment by iHiD** [comment]
Thanks. Closing and have a note in the project plan to check hotjars later.
