### ISSUE TITLE
Perhaps show text when there are no results after filtering

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#24]
When I go to the [C# side-exercises](https://v2.exercism.io/my/tracks/csharp#side-exercises) page and filter on exercises of length "Long", there are no matches. You can see that the number of exercises has changed to zero, but that is quite a subtle indicator. I think it would be better if some text was shown instead, like "No matching exercises found" or something like that.

**Comment by kytrinyx** [comment]
Yeah, we need to make sure we have empty states for everything where there might not be results or data yet.

**Comment by iHiD** [comment]
This is done.
