### ISSUE TITLE
Topic filtering of extra exercise doesn't work

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#25]
There are no topics displayed in the filter dropdown list of the [extra exercises page](https://v2.exercism.io/my/tracks/csharp#side-exercises). I also cannot just enter a topic and press enter to do any filtering: nothing happens.

**Comment by kytrinyx** [comment]
Thanks @ErikSchierboom!

Note: this is similar to https://github.com/exercism/v2-feedback/issues/8 which talks about the difficulty filter rather than the topics filter.

**Comment by iHiD** [comment]
This should now be fixed. Thanks for reporting.

**Comment by ErikSchierboom** [comment]
Excellent!
