### ISSUE TITLE
Improve concepts progress list display

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#26]
The sidebar to the right shows the list of concepts and your progress on them. However, the sorting used is not clear at first glance. I'm fairly positive that they are ordered by appearance in the config.json file, but I don't think most people will get this. I haven't yet submitted any exercises, so I suspect/hope they are sorted in descending order by completion percentage. However, if topics have the same completion percentage, maybe they should be sorted alphabetically?

As an aside, maybe it could be useful to show which concepts are still "locked," that is they are not present in any of the exercises you've already unlocked. Maybe show a lock icon or something like that, as people can then see/understand why they haven't yet seen the topic.

**Comment by kytrinyx** [comment]
This is great feedback, thank you 🌻

**Comment by iHiD** [comment]
They currently sort by completion percentage. Then they sort by the order they appear in exercises, where the exercises are sorted by core/not-core and then the position specified in the config.json (not through design - just what's happening). You get 10/10 for guessing! :) I'll add a second sorting phase for alphabetical.

> As an aside, maybe it could be useful to show which concepts are still "locked," that is they are not present in any of the exercises you've already unlocked. Maybe show a lock icon or something like that, as people can then see/understand why they haven't yet seen the topic.

That's a lovely idea.

**Comment by iHiD** [comment]
The ordering is now as you suggested (on master, not deployed yet). I've added the idea of the lock into our feature tracker. I'm going to close this now as it's the lock isn't blocking us, but I love it and will do it at some point :)

**Comment by ErikSchierboom** [comment]
Thanks!
