### ISSUE TITLE
There appears to be no maximum length to the Bio field

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#28]
It appears your bio can be arbitrarily long: https://v2.exercism.io/profiles/ErikSchierboom
For some reason I cannot paste any more data above a certain length, but I can still do individual key presses.

I think a maximum length would be better (for which the [`maxlength` attribute](https://www.w3schools.com/tags/att_textarea_maxlength.asp) can be used in the frontend).

**Comment by kytrinyx** [comment]
Thanks @ErikSchierboom. Keep these little details coming—this is really helpful.

**Comment by iHiD** [comment]
This should now be fixed. Thanks for reporting.

**Comment by ErikSchierboom** [comment]
I love how the help text shows my how many characters I currently have! Great touch.
