### ISSUE TITLE
Cannot close Update your profile page without updating

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#29]
If you open the Update your profile page, there is no way to close it other than clicking on the "Update profile" button. There should be other ways to close it, like a cancel button and/or close icon, pressing the escape key or clicking outside the pop-up window.

**Comment by kytrinyx** [comment]
Ah, yepp. We should be able to not update.

**Comment by iHiD** [comment]
Fixed. Thanks.
