### ISSUE TITLE
Languages are not listed consistently

### ISSUE THREAD

**Issue by tleen** [exercism/v2-feedback#3]
[#explore-languages](https://v2.exercism.io/#explore-languages) seems to be in a different order every reload. Is that on purpose?

**Comment by iHiD** [comment]
@tleen Yes. So the landing page is there as a visual indicator of all that exercism has to offer and I deliberately didn't want to prioritize any language over any other. We also considered that there is joy in trying to spot your logo and seeing what else you stumble across. 

However, once you're logged in and in "learning mode" in your head, things should be consistent and (from memory) alphabetical. 

Does that make sense to you?

**Comment by kytrinyx** [comment]
> However, once you're logged in and in "learning mode" in your head, things should be consistent and (from memory) alphabetical.

That is on the "Language Tracks" overview page that you get by default when you're logged in, btw.

**Comment by tleen** [comment]
I figured that may be the case. In the days of async JS you never know what is random by intention or random by timing. Languages random in feature is something I can see. Stability in ordering in a track overview is also good.

More of an intentionality check here. :+1:

**Comment by iHiD** [comment]
This is exactly the sort of thing that we really need people to be checking right now as it's so easy for us to have missed.  So thanks :)
