### ISSUE TITLE
Padding of copy button for CLI token

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#30]
The copy button's padding to the left makes it almost overlap the CLI token:

![image](https://user-images.githubusercontent.com/135246/29487354-ccf1a194-84f7-11e7-8601-05e6fb6d761f.png)

I feel like this padding should be the same as the padding to the left of the CLI token.

**Comment by kytrinyx** [comment]
Thanks for catching this, @ErikSchierboom

**Comment by iHiD** [comment]
This should now be fixed. Thanks for reporting.
