### ISSUE TITLE
How to leave a track

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#31]
You can join a track but it appears you can't (easily) leave a track. I think this should at least be an option for tracks you didn't submit any exercise for. Kinda like Hotel California... ;)

**Comment by kytrinyx** [comment]
This is a great point, thanks @ErikSchierboom!

**Comment by kytrinyx** [comment]
I've added this to our product/ux tracker for design discussions. Thank you!

**Comment by iHiD** [comment]
Added button. Thanks.
