### ISSUE TITLE
Privacy settings not clear

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#32]
On the privacy settings section of the Profile page, I can edit my privacy settings. However, there is no textual indication on what the checkbox does. Does checking it make me anonymous, or does it make me public?

**Comment by kytrinyx** [comment]
Great observation, thanks @ErikSchierboom!

**Comment by nicolechalmers** [comment]
For my reference https://v2.exercism.io/my/settings

**Comment by iHiD** [comment]
Hey @ErikSchierboom - we've updated this. I think it's lots clearer now so I'm closing this. Feel free to reopen if you still feel it's confusing :)

**Comment by ErikSchierboom** [comment]
Looking great!
