### ISSUE TITLE
Alignment of heart icon in footer is off

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#33]
The heart icon in the footer has a weird alignment that doesn't correspond to the rest of the text:

![image](https://user-images.githubusercontent.com/135246/29488956-ac43215c-8515-11e7-9528-682476f27bbc.png)

**Comment by NobbZ** [comment]
Seems to be related to your fonts…

It looks fine for me:

![hear-in-footer](https://user-images.githubusercontent.com/58951/29488991-53377b3e-8516-11e7-9e8a-28793d7c030b.png)
Chromes developer toolbar says that there are 3 fonts used to render that complete div (`.created-by`):

> Lato—Network resource(46 glyphs)
> Lato Light—Network resource(22 glyphs)
> DejaVu Sans—Local file(2 glyphs)

**Comment by ErikSchierboom** [comment]
Hmmm, for me it says:

> Lato—Network resource(46 glyphs)
> Lato Light—Network resource(22 glyphs)
> Segoe UI Emoji—Local file(1 glyph)

The latter is different. I'm on Windows 10 and on Chrome 60.0.3112.101 (64-bit)

**Comment by NobbZ** [comment]
Funtoo Linux with Chrome 60.0.3112.78 (Official Build) (64-bit)

**Comment by kytrinyx** [comment]
👍 good find, @ErikSchierboom.

**Comment by iHiD** [comment]
@ErikSchierboom Are there any sites that you know of that have the "Made by [red heart] ..." where this works nicely on your os/browser combo, that you could point me to pls?

**Comment by kytrinyx** [comment]
From my perspective, we don't need a [red] heart, just a heart :-)

Check out https://opensourcefriday.com/ and https://opensource.guide/

**Comment by ErikSchierboom** [comment]
The one @kytrinyx links to works perfectly!

**Comment by NobbZ** [comment]
Those are not unicode, but inline SVGs and therefore might again break on other browsers.

Perhaps use DejaVue Sans as web font (if available) and enforce it for the hard by wrapping it in a span? Perhaps license allows a stripped down version of that font?

**Comment by iHiD** [comment]
Yeah. So the one that's there at the moment is unicode, but Mac's love it and render it with textured colours and stuff (presumably magically through the font that @NobbZ mentions). We can use a font-awesome icon easily enough, but I wondered if anyone else had cracked this so it looked as nice as on the mac everywhere else.

For reference, this is what it looks like on Chrome on Mac.
<img width="1100" alt="screen shot 2017-08-19 at 22 42 40" src="https://user-images.githubusercontent.com/286476/29490286-bb8d72a6-852f-11e7-87fa-53a56a5d570a.png">

**Comment by NobbZ** [comment]
Perhaps you can check the font using chrome dev tools as well?

Personally I like the single colored icon most. It doesn't stand out that much on the page and fits better into the surrounding text.

**Comment by iHiD** [comment]
On Mac it's `Apple Color Emoji`, which is the default on Macs and iPhones for all unicode chars that the current font doesn't have a glyph for. It's very pretty :)

**Comment by kytrinyx** [comment]
I actually really like the idea of making it the same color as the rest of the text... but you know me and emoji! I'm going to defer to the design folks on this one.

**Comment by iHiD** [comment]
For clarity, this isn't a red heart. Apple's default font for the heart unicode character makes it red and gradient. But we'll change in Font awesome and then Nicole can decide about colour.

**Comment by iHiD** [comment]
This should now be fixed. Thanks for reporting.
