### ISSUE TITLE
[notifications] It's required from the user to manually mark notifications as read

### ISSUE THREAD

**Issue by ilya-khadykin** [exercism/v2-feedback#37]
It might be a small inconvenience, but still worth mentioning - it's required from the user to manually mark notifications as read. Just visiting the page with the comment by link doesn't mark it as read. Github handles this kind of thing perfectly well

![image](https://user-images.githubusercontent.com/6649477/29490264-71468c04-853f-11e7-8ed3-24d52b701e72.png)

**Comment by iHiD** [comment]
@m-a-ge Thanks. It should do what you suggest - it's a bug. I'll dig into it.

**Comment by Insti** [comment]
This may or may not be related but I have notifications that I cannot mark as read at all.

**Comment by NobbZ** [comment]
I have a notification that I can't dismiss as well, its about a reply to an approval comment, which was hand waving a fake submission. What kind of notification is it for you @Insti?

I can't neither dismis it by clicking the checkmark button, nor by clicking “mark all as read”.

**Comment by Insti** [comment]
There are 2 now, both are 'has posted a comment to a solution you are mentoring'

(both are to the same solution.)

**Comment by iHiD** [comment]
This should now be fixed. Thanks for reporting.
