### ISSUE TITLE
MD in comments not apparent until page is manually refreshed

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-feedback#38]
When posting a comment where a code snippet is included enclosed within ` ``` ``` ` the code highlighting doesn't occur once the post is made until the page is manually refreshed.  Highlighting does work if I preview the comment before posting.  Yes, I am including the language name after the initial ` ``` `.

**Comment by iHiD** [comment]
This is now fixed. Thanks for reporting! :)
