### ISSUE TITLE
Exercise naming inconsistency between site and CLI

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-feedback#39]
On the site exercises with `-` are replaced with spaces.  For the CLI the `-` are necessary, I presume.  This looks like an inconsistency to me.  Unless the CLI is OK with `hello world` or `hello-world`.

**Comment by kytrinyx** [comment]
Each exercise has a name and a slug. E.g. _Hello World_ is the name, and `hello-world` is the slug.

The name should be used when talking about it, but the slug should be used in the command examples.

Are you seeing `hello world` (explicitly lowercase) rather than `Hello World` anywhere?

**Comment by rpottsoh** [comment]
On the site, hello-world looks like **Hello World**.  As a new student to the site how is it communicated that with the CLI they will need to download the problem like so:
```
nextercism download hello-world
```

My point is that the title of the problem name displayed on the site is different from the slug.

**Comment by kytrinyx** [comment]
This is no different from how it is on the old site, and it is intentional.

Would you please help me understand where you are running into a problem?

**Comment by iHiD** [comment]
> As a new student to the site how is it communicated that with the CLI they will need to download the problem like so

It's on the instructions page here:

<img width="1176" alt="screen shot 2017-08-20 at 01 09 52" src="https://user-images.githubusercontent.com/286476/29490954-54b7e920-8544-11e7-8a72-32d63a40c720.png">


And the walkthrough here:

<img width="1209" alt="screen shot 2017-08-20 at 01 10 02" src="https://user-images.githubusercontent.com/286476/29490955-54ba7528-8544-11e7-8c88-27d6f9979bb3.png">

If that was unclear, we'll need to work on how to make it clearer. More details would be very appreciated.

**Comment by rpottsoh** [comment]
OK.  The confusion is mine.  Here is what happened and it stems from having been playing with the new site yesterday and not using the CLI at all, using just the fake tools to simulate the CLI.  I missed the instructions provided on the site for downloading the problem via the CLI.  The instructions are VERY obvious once I took a look at two-fer, and easy to follow. 

I don't know how much value there is in this, but it might be nice to have access to the download instructions after the student has performed a download.  The slug is only displayed in the download instruction window (with the copy button).  That information is gone once the download has been performed.  It might be useful to have a way to remind the student how to download, they may need to download it again if the test suite is ever updated.

**Comment by iHiD** [comment]
> have access to the download instructions after the student has performed a download. 

Note to self: Add a link back to the instructions page.
