### ISSUE TITLE
Privacy settings not giving correct error message when using duplicate handle

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-feedback#4]
Going through the motions of updating privacy settings on the Delphi Pascal Track is straight forward, however the changes are not being stored and/or are not being displayed.  Here are screen shots in order from how the relevant portion of the screen initially presents itself to how it appears once the process is finished.
![image](https://user-images.githubusercontent.com/6978003/29465419-3e00069c-8407-11e7-8ad3-613e95561bef.png)

![image](https://user-images.githubusercontent.com/6978003/29465428-462bc676-8407-11e7-9cf8-13b8a13d747b.png)

Disregard the `615x247`, an artifact from my grabber.   
![image](https://user-images.githubusercontent.com/6978003/29465443-555e68e2-8407-11e7-8a66-0a711fb37452.png)

![image](https://user-images.githubusercontent.com/6978003/29465447-5cf03b12-8407-11e7-9191-27eac15c1f59.png)

Upon returning to this screen, after leaving, the content is the same as the above image.

**Comment by iHiD** [comment]
Thanks for posting. I think the problem is occurring because you're choosing to enter a handle that is already taken (ie it's your primary handle not an anonymous one). The failure to save is therefore correct. The fact that you don't get an error message is clearly wrong! So I'll look into that. 

Out of interest, why were you entering your main handle here? Did that feel like the correct behavior in that situation or were you just experimenting?

**Comment by kytrinyx** [comment]
This is what I got when I chose a different handle than my username:

<img width="637" alt="screen shot 2017-08-18 at 9 26 37 am" src="https://user-images.githubusercontent.com/276834/29465698-6967bf60-83f7-11e7-9b0c-10781fbd0eab.png">

**Comment by rpottsoh** [comment]
>Out of interest, why were you entering your main handle here? Did that feel like the correct behavior in that situation or were you just experimenting?

I guess it wasn't clear to me.  Accidental experimentation.  :smile:   It is clear now, in hindsight.  I suggest, to be extra clear, to state that one should not use there account name as their `anonymous alias`.  Maybe even call it that.  Will they be allowed to use the same alias in more than one track?

**Comment by iHiD** [comment]
> Accidental experimentation.

The best kind :)

>  I suggest, to be extra clear, to state that one should not use there account name as their anonymous alias. 

Good idea.

> Will they be allowed to use the same alias in more than one track?

Currently no. That's not a massively considered decision though, so I'd be happy to discuss it if you feel it's something we should allow?

**Comment by kytrinyx** [comment]
I don't feel strongly about the ability to use the same alias on multiple tracks. I kind of think it's fine to make people come up with different aliases if they want to be anonymous.

**Comment by rpottsoh** [comment]
I don't feel strongly about it either.  It is probably less confusing (or safer) to prevent an alias from being used again on a different track, it could be used by a different person on a different track (not a good thing I think).  Would appear to some to be the same person on two different tracks and it could be two different people.

**Comment by kytrinyx** [comment]
Yeah, we could make it so that only the same person is allowed to reuse it, but it adds complexity for not necessarily a lot of value.

**Comment by iHiD** [comment]
>  The fact that you don't get an error message is clearly wrong! So I'll look into that.

Note to self. Update errors properly on one handle being a duplicate.

**Comment by iHiD** [comment]
This is now done. It'll be deployed later today or tomorrow. Thanks for reporting! :)
