### ISSUE TITLE
Mentor history?

### ISSUE THREAD

**Issue by Insti** [exercism/v2-feedback#41]
On the mentor dashboard it gives me some nice stats:

>You have mentored 9 solutions and helped 7 students since you became a mentor. 

But there does not seem to be a way to see what these solutions were, to re-check or come back for further comments.

I'm assuming they would show up as a notification if there was an additional comment, but I've not seen that happen, it may just be that no-one has commented after I've mentored.

**Comment by iHiD** [comment]
Hey @Insti - you should be able to filter on the drop down on the mentor page to find all the solutions you've mentored including ones that are completed, etc. If this doesn't work for you, please let me know. It might be nice to turn the "9 solutions" and "7 students" into links where you can explore further. I'll have a think about that.

**Comment by Insti** [comment]
Ok, that works, thanks. 

There's probably something that could be done to make the functionality more evident.

I must have explored that dropdown before I had any mentor exercises so I didn't realise it did anything.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
