### ISSUE TITLE
CLI on Windows: path cannot be specified with / separators

### ISSUE THREAD

**Issue by kytrinyx** [exercism/v2-feedback#43]
From @jonmcalder:

> From Command Prompt and Powershell:
> 
> nextercism CLI works both without args and when specifying the full path, but only if \ separators are used
> 
> Neither / or // seem to work as filepath/directory separators

@jonmcalder - does this mean that `/` does work as a file separator in Git Bash?

**Comment by kytrinyx** [comment]
My assumption is that `/` would not work on the Command Prompt and Powershell, since this is a Unix path separator, and that it _would_ work under Git Bash, since that is making Windows feel like *nix.

That said, I have never actually used a Windows machine :( so everything I think I know comes from reading stuff on the internet (which as we all know is terribly unreliable).

We could do a replacement on this. Is `/` is a legal path character on Windows machines?

@exercism/windows you might be able to help answer some questions here.

**Comment by NobbZ** [comment]
Modern windows versions (roughly since XP or Vista) do accept `/` as path sep. It is often the software built on top that has problem to deal with them, because only `\` is expected.

**Comment by kytrinyx** [comment]
@NobbZ 👍 cool, thanks! I'll write some tests to deal with them, then.

**Comment by robphoenix** [comment]
> I'll write some tests to deal with them, then.

@kytrinyx Have these tests been written? If not, I can add them in to the Appveyor branch.

**Comment by kytrinyx** [comment]
@robphoenix I honestly can't remember. Probably not...? It's been a rough few weeks.

**Comment by robphoenix** [comment]
@kytrinyx Hey, no worries. I'll look at adding some tests. Take care of yourself.
