### ISSUE TITLE
CLI on Windows: Is possible to store hanging " in workspace path

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-feedback#45]
When using CMD:
If a learner's workspace location contains spaces the workspace must be configured like so:
```
nextercism c -w "c:\my nextercism"
```
This in itself is not a problem.
`nextercism c -s` yields:
```
Config dir:      C:\Users\Ryan Potts\AppData\Roaming\exercism
-t, --token      {removed}
-w, --workspace  c:\my nextercism
-a, --api        https://api.exercism.io/v1
``` 
An issue does result if the learner programs the workspace like so:
```
nextercism c -w "c:\my nextercism\"
```
The trailing `\` creates the problem.  `c -s` yields
```
Config dir:      C:\Users\Ryan Potts\AppData\Roaming\exercism
-t, --token      {removed}
-w, --workspace  c:\my nextercism"
-a, --api        https://api.exercism.io/v1
```
The trailing `"` is a problem.  The phenomenon is not isolated to paths that contain spaces.  Any paths enclosed in `"`s that contain a trailing `\`.

**Comment by kytrinyx** [comment]
Out of curiosity, what do you get if you dump the contents of the config file (with the token redacted)?

```
C:\Users\Ryan Potts\AppData\Roaming\exercism\user.json
```

There's some weirdness going on with the backslashes, I think. Backslash is an escape character, so I'm not exactly sure why it would work on the first slash but not on the last one. Presumably because `\m` is meaningless?

I wish I understood the subtleties of this better!

**Comment by rpottsoh** [comment]
After `nextercism c -w "c:\nextercism\"` `user.json` appears as so:
```
{"Workspace":"c:\\nextercism\"","Token":"removed","Home":"C:\\Users\\Ryan Potts"}
```
After `nextercism c -w c:\nextercism` `user.json` appears as so:
```
{"Workspace":"c:\\nextercism","Token":"removed","Home":"C:\\Users\\Ryan Potts"}
```

**Comment by NobbZ** [comment]
Cmd at least (never tried powershell) does always take backslashes literally, `\"` is the only exception I'm aware of. This is done because of the meaning of back slash as a path separator.
