### ISSUE TITLE
[minor] Ruby icon orientation.

### ISSUE THREAD

**Issue by Insti** [exercism/v2-feedback#46]
Traditionally the ruby Icon is tilted but the Exercism version is vertical.
Could we try rotating the Ruby in the icon counter clockwise?
(Maybe 60 degrees? but I'm not a designer.)

**Comment by iHiD** [comment]
@Insti Thanks for raising. Would you mind opening this on [the icons repo](https://github.com/exercism/website-icons) please? Sorry to be a nuisance. It'll get dealt with for you there.
