### ISSUE TITLE
Ruby blurb update

### ISSUE THREAD

**Issue by Insti** [exercism/v2-feedback#47]
We've update the blurb in the [Ruby config.json](https://github.com/exercism/ruby/blob/master/config.json#L4) but [the site](https://v2.exercism.io/tracks/ruby) is still showing the "TODO" text.

**Comment by iHiD** [comment]
Thanks for reporting. There seems to be some issue with caches not
expiring. @ccare will take a look when he's back from holiday tomorrow.

**Comment by ccare** [comment]
@Insti @iHiD hopefully, that's now looking a little better now? Thanks for identifying the issue

**Comment by Insti** [comment]
Blurb is updated now. Thanks.
I'll open another issue if I discover any other caching issues.
