### ISSUE TITLE
Profile page only shows completed exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#49]
My profile page appears to only show me completed exercises, but I would like to also be able to find my incomplete exercises. Perhaps a filter should be added to allow filtering on Complete/Incomplete/All?

**Comment by NobbZ** [comment]
Not complete, but published solutions.

The public profile is just that. Public. With an edit button that you are the only one who sees it.

To see your in-progress or unpublished solutions you have to go one the corresponding tracks page.

But a more birdlike overview of everything like in v1 profile would be nice. And if we could filter there as suggested in #51 for the public profile (comments, reactions, etc) it would be even cooler

**Comment by ErikSchierboom** [comment]
Ah, I was perhaps making the wrong conclusion then based on the page's sub header:

> This is a showcase of some of the solutions that Erik Schierboom has **submitted** on Exercism.

**Comment by iHiD** [comment]
> But a more birdlike overview of everything like in v1 profile would be nice.

Noted. There is a dashboard coming, which will be a lot of mixture of notifcations, where you left off, etc. That probably won't be before public release though. A historic overview page is a good idea too. I'll add it to our tracker.

> Ah, I was perhaps making the wrong conclusion then based on the page's sub header:

We'll update that.

**Comment by iHiD** [comment]
I've updated the header. The dashboard is in our product-tracker so I'll close this for now. Thanks for the discussion.
