### ISSUE TITLE
Tagline at bottom of site indicates 0 Volunteers

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-feedback#5]
![image](https://user-images.githubusercontent.com/6978003/29466206-fbd59a72-8409-11e7-8c94-b0b1255ccd59.png)

**Comment by kytrinyx** [comment]
Oops. We must not have run the contributor script after we deleted all the data last night. We'll get on that!

**Comment by iHiD** [comment]
Ah. We've not run a seeding script. Thank you!

**Comment by iHiD** [comment]
The 1,227 wonderful volunteers are now back on the bottom. Thanks! I'm closing this but if it ever defaults back to zero, please reopen it!
