### ISSUE TITLE
Allow filtering on status/comments on profile page

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#51]
The profile page shows my solutions. Perhaps it would be useful to be able to filter on the solution "status" (thumb, heart, genius) or on solutions that have one or more comments.

**Comment by iHiD** [comment]
We'll do this, but not until all the bugs are fixed :)

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
