### ISSUE TITLE
Exercises on Exercises Unlocked page are not links

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#52]
When completing an exercise, the Exercises Unlocked pages (which looks great BTW) shows the exercises that are unlocked. Weirdly enough, I cannot click on any of the exercises, which I would like to do because the exercise page contains the download instruction for that exercise.

**Comment by iHiD** [comment]
For clarity, this is on the final of the three modal stages? I hadn't considered that those should be links. Nice idea :) I'll discuss with the product team and get back to you here.

**Comment by ErikSchierboom** [comment]
Yes I believe it was.

**Comment by iHiD** [comment]
After discussion in #54, I'm going to add some hover titles here and also make it so when you click the icon it opens the exercise in a new tab (the best or worst of worlds depending on one's opinion). I think that's the most ideomatic way of handling the modal vs web-page thing and also allowing the requisite functionality, which I think is also important.

**Comment by ErikSchierboom** [comment]
I'm fine with that!

**Comment by iHiD** [comment]
This is now done. It'll be deployed later today or tomorrow :)
