### ISSUE TITLE
mentoring: images in notification email not displayed

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#53]
In the notification email about a comment of a mentor, there is no image displayed. Inbox by GMail (Web) doesn't show it at all, while the Android App at least shows one "missing image"-replacer above the emails text.

While observing the mails source, I noticed 2 `<img src="/assets/mailers/*.png"…>` in the mail.

Perhaps it is because the host missing in the mail, but I'd prefer embedded pictures over served ones. Many MUAs block HTTP-requests to avoid tracking.

**edit**
Because it is the {path => host} missing…

**Comment by kytrinyx** [comment]
Thanks @NobbZ

**Comment by ccare** [comment]
Hi @NobbZ, this should now be fixed. You were correct, it was a missing the host configuration. 

Your point about inlining images is interesting. I'll talk to @iHiD about that, but I suspect that would be an enhancement to consider after the beta stage.
