### ISSUE TITLE
[Exercises Unlocked]: Initial Reaction

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-feedback#54]
Here is what I saw when I unlocked Two Fer
![image](https://user-images.githubusercontent.com/6978003/29534725-0ecb758e-8685-11e7-8850-a43202781358.png)

My initial reaction is that I like what I see.  I would, however, like to make a couple of suggestions.

1. The title `Exercises Unlocked` implies plural.  Is it possible for this window to be presented if/when more than one exercises is unlocked at a time?
2. It might be good if when the icons (the ones I circled) are hovered over that their icons be replaced with the actual names of the exercises.  All of the glyphs may not be as intuitive as others to infer their meaning.

**Comment by rpottsoh** [comment]
I must add getting an email that an exercise was just commented on by a mentor was very cool.  :1st_place_medal:

**Comment by kytrinyx** [comment]
@rpottsoh this is also related to https://github.com/exercism/v2-feedback/issues/52

**Comment by rpottsoh** [comment]
It is related.  I would say that since this is a modal screen that unlocked icons should not be links, but I still like my hover idea to display the exercise names.

I am not sure that #52 is relating to this exact screen.

**Comment by BethanyG** [comment]
So..this is also related, I think.....I just 'completed' and exercise on the Java track, and was messaged that 'Raindrops' was unlocked as optional....but then this is what showed up on the Main Track Page:

![screen shot 2017-08-22 at 11 01 11 am](https://user-images.githubusercontent.com/5923094/29580131-cc6c7d14-8729-11e7-8edd-f50e537d90b8.png)

So the exercise is mis-classed as a milestone...

**I take it back...this is it's own issue**  Will log it as such.

**Comment by ErikSchierboom** [comment]
> I would say that since this is a modal screen that unlocked icons should not be links,

May I ask why? It is just a webpage, only with a smaller size. I think a modal screen should still follow general HTML guidelines, which means linking to specific pages when possible.

**Comment by NobbZ** [comment]
And if we don't get links, please do give us at least some mouse-over hints…

**Comment by rpottsoh** [comment]
@ErikSchierboom I'm not a web designer.  I am not really familiar with HTML guidelines.  To me the small HTML page is intended be a modal dialog, to make an announcement, and nothing more.  Within the scope of that announcement it might be nice, while hovering over the icons, that they reveal the names of the exercises they represent.  Having the announcement perform any other function than what it was intended sounds like scope creep to me.  The screen the announcement returns you to is the intended launching point for exercises.  I won't be offended if the decision is to turn the icons into actual links.  I'm just tossing in my 2 cents.

**Comment by NobbZ** [comment]
> It might be good if when the icons (the ones I circled) are hovered over that their icons be replaced with the actual names of the exercises. All of the glyphs may not be as intuitive as others to infer their meaning.

Also I can't find those glyphs via `C-f`. I've to scan that huge list of cards manually for an icon. Thats a tough one…

**Comment by iHiD** [comment]
> The title Exercises Unlocked implies plural. Is it possible for this window to be presented if/when more than one exercises is unlocked at a time?

@rpottsoh I'm slightly confused by that question. Three exercises are unlocked - one core and two bonus. So you are seeing it presented when more than one exercise is unlocked a time. 

Could you explain further please. 

I'll deal with the second half in #52 :)

**Comment by rpottsoh** [comment]
@iHiD I understand your confusion in my question now that it has been a few days since I posted it.  I'd be confused too.  At the time I was just considering the announcement to be for the main exercise being announced as unlocked and not the bonus exercises.  I don't know why I didn't consider the bonuses in the whole scope of things. :(

**Comment by iHiD** [comment]
> At the time I was just considering the announcement to be for the main exercise being announced as unlocked and not the bonus exercises.

@rpottsoh If you found it confusing, then most other people will too! I'll have a chat with the team to see if we can make this clearer :) I'll close this issue and add it to our internal product-tracking stuff. Thank you for your help 💙
