### ISSUE TITLE
[minor] strange behaviour of an element with code solution snippet on 'Review Solution' Page while scrolling down

### ISSUE THREAD

**Issue by ilya-khadykin** [exercism/v2-feedback#55]
This is probably a minor issue.

**Page**: 'Review Solution' Page (Mentor role)
**Reproducible on**:
* Google Chrome
* Microsoft Edge

**Screen capture**:

<details>

![](http://g.recordit.co/VSWSGl5UKU.gif)

</details>

**Comment by NobbZ** [comment]
Related to #20?

**Comment by kytrinyx** [comment]
Thanks @m-a-ge. I updated your post to hide the gif in a `<details>` section, since I find it difficult to read when stuff is moving 🌷

**Comment by ilya-khadykin** [comment]
@NobbZ, yeah, seems that way.
Would you mind adding the gif from this issue to yours and I'll close this one

**Comment by ilya-khadykin** [comment]
@kytrinyx, thanks! I didn't know that Github supports this tab :open_mouth:

**Comment by ilya-khadykin** [comment]
Closing this in favor of #20
