### ISSUE TITLE
mentoring: can't approve without comment

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#56]
There is a button missing that simply approves a solution.

Currently I can only "comment" or "comment and approve", both buttons do nothing if the comment box is left empty.

Also I do feel a "well done"-comment is redundant to "approve" clicks

**Comment by kytrinyx** [comment]
GitHub does this nicely. If you haven't written anything in the comment field, the button says "close issue". If you add something to the text box, it turns into "close and comment".

**Comment by iHiD** [comment]
> GitHub does this nicely. If you haven't written anything in the comment field, the button says "close issue". If you add something to the text box, it turns into "close and comment".

I've implemented it exactly like this. 

@NobbZ I've also added a little indicator below the comment box that shows if the solution is approved. We might design that up better but it's there for now to be helpful :)
