### ISSUE TITLE
mentoring: download the mentored solution for local test-runs

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#57]
When I want to pull a solution I am mentoring to let the tests run locally, I need to extract the UUID from the URL.

It would be nice if there were a box that let me copy a download command that is ready to paste and run for my shell, as we have such command beneath every unlocked but not solved exercise as a student.

**Comment by kytrinyx** [comment]
Yeah, we should definitely add the easy copy button. I've meant to add the behavior so you can copy/paste the URL and we'd extract the UUID from that as well, but I think the copy box would be better overall.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
