### ISSUE TITLE
cli: make download subcommand print only target folder

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#58]
If `exercism d ...` were only printing its last line, I'd be able to do `cd $(exercism d ...)` But currently I have to do `cd $(exercism d ... | tail -1)` and to rely on errors beeing printed to stderr…

**Comment by kytrinyx** [comment]
We're eventually probably going to have more text, but what if all the extra text went to STDERR and only the URL went to STDOUT?

I feel like "notices" are perfectly reasonable to have in STDERR (not just errors).
