### ISSUE TITLE
web-UI has no fav-icon.

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#59]
There needs to be one ;)

**Comment by kytrinyx** [comment]
Yes! This is a definite requirement. This is a major blocker for public launch...

**Comment by NobbZ** [comment]
Will a shrinked version of “curly” fit?

**Comment by kytrinyx** [comment]
Not sure—this will have to be up to the designer.

**Comment by iHiD** [comment]
Thanks. This is on now on my pre-launch list.

**Comment by iHiD** [comment]
Done. Thanks.
