### ISSUE TITLE
“curly” needs a name

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#60]
The cute new logo-mascot needs an official name. For now I call it “curly” because its made from curly brackets, but I hope there will be better ideas around…

**Comment by javierxavila** [comment]
curly is a perfect name

**Comment by FabienTregan** [comment]
I've secretly called it "Devly". Because it's a contraction of Developper and Curly.
Not because is sounds as Devil like Exercism sounds as Exorcism. No at all.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
