### ISSUE TITLE
mentoring: Solution mentored by someone else but not improved by student still hogging my todo list

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#63]
Currently there is a submission in my “next to mentor” list, which has been mentored "1 day ago". The student has neither replied so far, nor has he improved his submission.

After a launch, when there are many students that lost interest after first submission, this will massively polute the mentors queue with phantoms and it will be hard to find the real ones that need to get reviewed.

Possible solutions:

1. Do not show submissions that have already been mentored by at least one mentor.
2. Move it into “waiting for them” (which I prefer to read “waiting for the student”)
3. Create a new queue which makes clear that the submission “belongs” to another mentor, but is waiting for the student

**Comment by iHiD** [comment]
> Move it into “waiting for them” (which I prefer to read “waiting for the student”)

This should be the case (and I agree with your wording). Could you paste the solution uuid and I'll investigate please?

**Comment by NobbZ** [comment]
The one I've found is `8a4093aa-ca14-45ec-a10f-89f5a4222cc5`.

**Comment by iHiD** [comment]
Oh. Sorry. I've misinterpreted what you said. This is in the list of solutions that aren't yet mentored. This is more complex then.

At the moment posts appear in this list until 3 mentors have replied. (ie, 3 different bits of feedback might be useful). They should be ordered by priority with this lowered if someone has already mentored. I'll check into the specific solution in a bit, but would appreciate @kytrinyx's input on this to confirm whether this behaviour is still what we considered correct during the product design phase.

**Comment by iHiD** [comment]
Sorry for the multiple posts. Reading the code, things are ordered by: 
1) number of mentors mentoring this solution (fewest first)
2) last time person replied (earliest first)

We could not show things in this "needs mentoring" list if the student hasn't replied since the last mentor interaction. However, this will increase the likelyhood that solutions only get assigned one mentor. This isn't a straight-forward one - lots of tradeoffs.

Thoughts @NobbZ, @kytrinyx?

**Comment by kytrinyx** [comment]
> This isn't a straight-forward one - lots of tradeoffs.

Yeah, agreed.

I really would like people to be able to have feedback from more than one person. People often have different insights, different backgrounds, and different things that they focus on.

I do wonder what this will look like with lots of activity—there will presumably be lots of solutions available to give feedback to where there are no mentors, and so those would be prioritized first.

**Comment by iHiD** [comment]
> there will presumably be lots of solutions available to give feedback to where there are no mentors, and so those would be prioritized first.

That was how we designed it. Yeah. I wonder if we need to show on the mentoring screen how many mentors are on a solution to make this work for mentors? And also we need a way for mentors to remove solutions from this queue.

**Comment by kytrinyx** [comment]
> I wonder if we need to show on the mentoring screen how many mentors are on a solution to make this work for mentors?

Yeah, that sounds sensible.

> And also we need a way for mentors to remove solutions from this queue.

Right! "nothing to add here" is probably a common scenario.

**Comment by NobbZ** [comment]
I like the idea of a second opinion as well, basically the third option I gave had that in mind. Therefore:

I like the “nothing to add” button which makes it disappear from my list, but still gives other mentors the possibility to chime in. :+1: 

Also I like them beeing lower priotized. So I can assume that when I hit such a submission, that all “open” mentorings have been taken, and from now on only “co-mentoring” will happen?

----

But now I have to wonder about, what will happen when two mentors give contrary advices? Who has to accept the final submission? What if mentor A has to complain a lot, while B thinks everything is fine and approves the submission ignoring As wall of text?

**Comment by iHiD** [comment]
> Also I like them beeing lower priotized. So I can assume that when I hit such a submission, that all “open” mentorings have been taken, and from now on only “co-mentoring” will happen?

Correct. If not, it's a bug.

> But now I have to wonder about, what will happen when two mentors give contrary advices? Who has to accept the final submission? What if mentor A has to complain a lot, while B thinks everything is fine and approves the submission ignoring As wall of text?

Either person can accept. We'll have to see how this emerges I think. I would suggest that in the case you give one mentor would be "wrong". We need to review and then advise the mentor accordingly.

> I like the “nothing to add” button which makes it disappear from my list, but still gives other mentors the possibility to chime in. 

I'm implementing that now.

**Comment by iHiD** [comment]
Done and deployed.
