### ISSUE TITLE
track-maintanace: will journey-script-tests continue to work?

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#64]
From my userpoint of view, the process of retrieving has changed massively, I now do even need approval by a mentor.

But from a track-maintainers way, who uses a journey-script for testing the track, it worries me.

Those journey-scripts set up a mini-exercism on travis, which does only know about a single track. Also the CLI is used to fetch exercises from the mini-exercism. 

This way of testing does not only ensure, that the tests and example solution do work, but also that all files are served correctly (not getting mangled because of symlink, or accidentaly match ignore pattern, etc).

Will such a script still be possible with nextercism CLI and API? I do not mind to change it a bit to make it suite the new CLI commands or because the mini-exercism has to be set up differently, I mean in general… Or do I need to go back to a script which simply walks the file tree and runs the test without pulling them?

**Comment by kytrinyx** [comment]
This is a really good observation, @NobbZ!

I would like to think about a way to make it possible to spin up a very small API so that the journey tests still work.

I need to think for a bit about the best way to accomplish it, but it would be very valuable to have a journey test that we could plug any track into and interact with each of the exercises.

**Comment by petertseng** [comment]
now that there is less dynamic work being done ([no more readme generation](https://github.com/exercism/meta/issues/15)) it is possible that many problems that were previously only checkable via the journey test are now testable via tools that do not require the API.

For example, the most pressing issue was that tracks may intend to have an exercise based off of problem-specifications but have misspelled the exercise slug. This is no longer a problem.

Knowing the nature of the remaining problems where it is useful to have the API will help prioritise this.

**Comment by NobbZ** [comment]
But this might still discover accidental symlinking in a repo instead of copying.

**Comment by kytrinyx** [comment]
> But this might still discover accidental symlinking in a repo instead of copying.

Is this something that configlet could figure out? Or asked differently, do you have an example of what that looks like?

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
