### ISSUE TITLE
Exercise Card: How is length determined?

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#65]
What is the “length” on an exercises card? Currently I've not seen any that displays a value different from “short”…

**Comment by ErikSchierboom** [comment]
I have the exact same question :)

**Comment by iHiD** [comment]
It's not yet :)

Once ETL is done then I'll work that one out, but I need data to look at it. Probably something basic like average number of attempts for now.

**Comment by iHiD** [comment]
I've added this to our internal tracker. Thanks.
