### ISSUE TITLE
v2 is inaccessible for the visually impaired

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#67]
Besides of the low contrast/small fonts thing mentioned in #66, I did some tests using a testbrowser to simulate what a blind person whit a braille terminal would roughly “see”.

---

The tracks dashboard/my tracks site, is a hard to grasp list of words lacking context, I'm able to roughly guess where to click to enter a track though…

<details><summary>Screenshot</summary>

![my-tracks](https://user-images.githubusercontent.com/58951/29608496-9c431bea-87f4-11e7-9edf-84f7dc02e30f.png)

</details>

----

So I entered the erlang track, which gave me a blob nearly indistinguishable exercises with their corresponding “lock” status and number. There's been no way to actually select or click those exercises.

<details><summary>Screenshot</summary>

![erlang](https://user-images.githubusercontent.com/58951/29608533-b8a2e298-87f4-11e7-8dd9-65fba59cbcc5.png)

</details>

---

Also I was unable to find a link or an indicator to/about notifications.

<details><summary>Screenshot</summary>

![notifications-missing](https://user-images.githubusercontent.com/58951/29608969-0bb580f2-87f6-11e7-89a2-fc0e6aa727b0.png)

</details>

**Comment by iHiD** [comment]
Thanks for posting, @NobbZ.

I would like to make a whole different low-accessibly version of the site that's really optimised. However, for now, this isn't going to be easily fixable, so I'm going to mark it as wont-fix in the context of the prototype, but it's something I'd like to readdress in the medium term.

**Comment by kytrinyx** [comment]
I also need to reach out to an acquaintance of mine who has a lot of experience with accessibility work to see if she has a couple of spare hours to give us towards a complete evaluation.
