### ISSUE TITLE
[notifications] Some notifiactions can't get deleted

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#68]
As already said in #37 some notifications can't be marked as read.

For me it is a notifications about an answer in an solution that I've approved as a mentor. The same solution does also appear in "requires action from you" on my mentoring page as I have realised a couple of minutes before.

**Comment by NobbZ** [comment]
After adding another comment to that solution, the mentoring request is in “waiting for them”, notification still there and not beeing able to dismiss it… I opened another issue because of the mentoring request: #69

**Comment by Insti** [comment]
I have 2 notifications I cannot dismiss, both are 'has posted a comment to a solution you are mentoring' and both are for the same solution.

**Comment by iHiD** [comment]
This should now be fixed. Thanks for reporting.

**Comment by NobbZ** [comment]
Now we seem to be back at v1 behaviour where one was able to delete notifications by accident... Just by visiting a solution, perhaps it was opened as last tab in my browser, notification is lost then. As a mentor I will probably miss students replies, or as a student I miss the mentors comment.

**Comment by iHiD** [comment]
That's the same behaviour as Github, which is what I've mirrored. Let's try it and see what happens and we can reevaluate the decisions once we've got a larger consensus of users using it.

**Comment by NobbZ** [comment]
Never realised it were that way in github, I just use email notifications and bulk-delete/ignore the notifications on the page...

**Comment by kytrinyx** [comment]
> I just use email notifications and bulk-delete/ignore the notifications on the page...

If you don't use the site notifications you can turn them off entirely.
