### ISSUE TITLE
mentoring: replies to approvals break the process-flow

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#69]
I approved a sulution, which was in “completed” then (I'm pretty sure at least), the student replied to my comment though, which moved the solution back to “requires action from you".

All I was able to do was to do an ordinary comment. That comment moved the solution to "waiting for them".

There has been no reply so far, but I fear that there will be no way to get this already approved solution back into “completed”…

**Comment by kytrinyx** [comment]
Thanks, @NobbZ this sounds like a bug, so marking it as such until we can confirm otherwise.

**Comment by NobbZ** [comment]
@nicolechalmers can you answer in that conversation?

**Comment by iHiD** [comment]
@NobbZ Do you have the solution id?

**Comment by NobbZ** [comment]
Of course: `1c13f3eb-65fe-4ccb-9900-f5c92421bbb5`

**Comment by iHiD** [comment]
The student has not completed it. We'll add some extra status flag on the mentor page that shows this for you.

**Comment by NobbZ** [comment]
I'm pretty sure though, that it was displayed in the “completed” filter, as every solution that I've approved so far was “completed” instantly if I've observed that right…

I really have to take a closer look when approving the next one…

**Comment by NobbZ** [comment]
OK, I was able to approve another solution. Its under “waiting for them” right after approval. It seems as if I was just to slow back then, when looking at the others.

But yes, some kind of indicator in which state a solution is, would be nice.

Perhaps trafficlights?

* **red**: waiting for approval
* **yellow**: approved, but not completed
* **green**: completed by the student
* (**blue**): completed and published

**Comment by NobbZ** [comment]
@nicolechalmers marked the exercise as complete she told me in the comments, but it is shown as "requires action from you" now.

Also I got another indismissable notification...

**Comment by NobbZ** [comment]
After #68 has been fixed, notifications are gone, still the solutions is listed as "requires action from you", so it seems as if the process-flow got broken somehow. This may be a generic problem or related to this particular conversation,

I can't tell if the solution was in "completed" before @nicolechalmers replied in that conversation that she "completed" now. I can only tell that it now waits for me to take action.

**Comment by iHiD** [comment]
This should be fixed for new solutions. I've also manually fixed it for the old solutions. I've added the status to our product-tracker.

 @nobbz - Please open if you see this continue. Thanks for the detailed help with fixing it.
