### ISSUE TITLE
Do not display only the full name in profile per default

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#7]
In the profile the full name is shown. Even though this helps against “anonymous vandalism”, I do not think it is a good thing.

When I read “Norbert Melzer” it feels like looking at someone elses profile. In the internet I'm known as NobbZ, even my parents, my wife, my son, and of course my co-workers are calling me by this name.

I think displaying the nickname fullsize and full name in a slightly lighter shade and smaller below that would still make clear that one isn't anonymous but making it possible to recognize the profile of people that one does only know via their nicknames.

**Comment by NobbZ** [comment]
Seems actually to be even inconsistent with other views where I do see the users nickname, but on the profile page I can only see his full name. This is even more disturbing.

For some nicks one will probably not even realize the difference (norbertmelzer vs. Norbert Melzer, no-one cares for that difference), but when nickname and fullname are totally different as for me or kytrynix or m-a-ge its getting in the way.

**Comment by kytrinyx** [comment]
Acknowledged—many people are known by their handles and monikers more than their full names on the internet.

I agree that consistency is desirable.

I'm adding this to our list of things to discuss from a UX/design perspective, thanks for the feedback.

**Comment by kytrinyx** [comment]
Thanks, @NobbZ. I've added this to the product/UX tracker.

**Comment by iHiD** [comment]
@NobbZ Thanks for reporting this :)

Just to keep you updated, I've updated things to show the handle everywhere except the profile. We're giving the option for either on the profile, but we've not done this bit yet. I'll update this once we have. If you see your name appear anywhere around the site that's not the profile, then it's a bug, so please report it on this thread.

**Comment by iHiD** [comment]
You now have options when creating and editing your profile to change your display name.
