### ISSUE TITLE
commenting: none-monospaced font makes commenting with code hard

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#70]
This is something I already disliked at the old version, but never cared for since most of the comment is simply prose, but now since we have some highlighting/coloring for the comment-edit-box, it would be nice if code-blocks were displayed with a monospaced font. I do not think that we need to color according to the language in edit mode, but at least monospaced display.

![no-monospaced-font](https://user-images.githubusercontent.com/58951/29610793-a2a49ed0-87fb-11e7-97f5-87a2ff5dcd10.png)

Currently code does only get some slightly darker background which I only recognize as different if I get very close to my monitor (uncalibrated setup)

**Comment by kytrinyx** [comment]
I'd like a monospace font for code in the comments, as well. (Agreed that we don't need syntax highlighting for it).

**Comment by iHiD** [comment]
Done
