### ISSUE TITLE
mentoring: go straight to UUID

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#71]
As a mentor, a student or a mentor gave me an UUID for a second opinion, I'd like to be able to go straight to that solution without having to assemble the URL on my own.

**Comment by kytrinyx** [comment]
@NobbZ Can you elaborate a bit on the use case? Where did they give you the uuid? (Outside the website, e.g. chat, perhaps?)

Would it work to have a `--uuid` flag on the open command, so you could say `nexercism o --uuid <paste>`?

[Edited command, because... typos]

**Comment by NobbZ** [comment]
In a chat, or perhaps a co-worker by mouth/paper, some external service. I'm not really sure.

But aside from the channel used to communicate, I do think that such a feature is especially important for inter-mentor communication and asking for a second opinion.

I do not think that it is important for students, which could try to "pick" a more forgiving mentor this way.

But yes, I do think a subcommand would suffice, but when we use `open` for it, will `open` be able to distinguish between my own solutions, those published by someoneelse and those that need review? (Well I'm aware of the fact that UUIDs are **U**niversaly **U**nique ;) )

**Comment by kytrinyx** [comment]
will open be able to distinguish between my own solutions, those published by someoneelse and those that need review? 

Yeah, we have logic to open this for you in your own context if it's yours, the mentor context if you have access to it as a mentor, and public context if it's published and neither of the above are true.

**Comment by iHiD** [comment]
@NobbZ Are you seeing this as a CLI modification or a website modification?

**Comment by NobbZ** [comment]
It depends on the way to go ;)

If we introduce `nextercism open --uuid` its clearly CLI, if we add a textfield on the mentoring dashboard its probably website.

For me it does not make much difference, I'm fluent with the terminal as well as my browser. Other people might prefer one over the other though.

I have to say though, that I really would like to have it in the CLI, because then I can script a lot into it... `mentor $uuid` could then pull the solution, switch directory and then open it in the browser... Well, but then I'd like to ask for URL only even more, because then I can even script if an existing browser session should be used or a new one created on the current screen, so in general `open` subcommand should be able to either open or print URL only)
