### ISSUE TITLE
commenting: edit comments

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#72]
As a mentor I made a typo in the code-portion of a reply and want to fix it, but there is no option to edit a comment at all.

As a student I realized a typo in a word which makes the hole sentence ununderstandable, I want to fix it, but there is no option to edit a comment at all.

Therefore I think we should enable editing of comments, as we had already on v1, but this time lets keep the history. By keeping the history we still avoid the "make things never had happened" while giving the opportunity to fix things that are necessary to fix.

**Comment by kytrinyx** [comment]
Thanks for the suggestion, @NobbZ!

**Comment by pgaspar** [comment]
I also ran into this problem when testing today. Typos are the worst, specially when you notice them 2 seconds after submitting the comment.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
