### ISSUE TITLE
notifications: breadcrumb feels odd

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#74]
As a user I am visiting my notification page and see the breadcrumb “Language Tracks > Notifications”. This feels a bit odd, since those notifications aren't related to only language tracks but to mentoring also (which got its own breadcrumb namespace), I think we should therefore create a namespace on its own for notifications or a complete new Top-Level which will have the children languages, notifications, and mentoring.

**Comment by kytrinyx** [comment]
Good catch, thanks!

**Comment by iHiD** [comment]
To explain the current situation, everything will eventually be based from a "Dashboard" base, but we don't have that page done yet, so we're giving the current homepage (tracks) as the base. But yes, this will change. Thanks for raising it.

**Comment by iHiD** [comment]
I've removed the "Language Tracks" for now.
