### ISSUE TITLE
notifications: show a counter

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#75]
Since I do have the opportunity to explicitely not dismiss a notification to come back to it later for further review, it would be nice if there was a count displayed with the bell-icon.

**Comment by kytrinyx** [comment]
I think we might need to understand this use case better. That is not to say we might not make the change, but my suspicion is that we could design something even better for this use case.

**Comment by NobbZ** [comment]
Yeah, maybe... Perhaps ist just the read dot confusing me because I'm unable to dismiss notifications. This really makes me wish there were an indicator telling me how many notifications are waiting there, so I could calculate a delta in my head and take a look if the delta is not equal to zero.

Another thing is, I'm just used to having a marker which tells me the number of notifications. Be it the v1-side, be it google, be it outlook, be it twitter on my mobile, be it phpBB or discourse. All are showing me an actual notification count, not just an indicator.

**Comment by kytrinyx** [comment]
> All are showing me an actual notification count, not just an indicator.

I've turned off notifications for GitHub (I use email notifications exclusively there), but my recollection is that there is an indicator but no notification count.

**Comment by iHiD** [comment]
>  but my recollection is that there is an indicator but no notification count.

Correct

<img width="167" alt="screen shot 2017-08-24 at 16 39 47" src="https://user-images.githubusercontent.com/286476/29674709-dcc037ec-88ea-11e7-9734-98c4b380683e.png">

> Perhaps ist just the read dot confusing me because I'm unable to dismiss notifications. This really makes me wish there were an indicator telling me how many notifications are waiting there, so I could calculate a delta in my head and take a look if the delta is not equal to zero.

Yeah - I think so. The dismissing notifications bug should be fixed now for you.

We're going to launch with just the dot but we can always add the number in later down the road if we think it needs it once we've had some experience of users using it properly. I'm going to close this for now. Thanks for opening.

**Comment by Insti** [comment]
+1 on a counter.
