### ISSUE TITLE
contributors page: clicking a contributor leads to 404 on github

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#76]
As a user, when I visit https://v2.exercism.io/team and click on one of thr small cards in the contributors section, then I get a 404 from github.

The links all have a `/1` appended which invalidates them, eg: https://github.com/NobbZ/1 (404) vs. https://github.com/NobbZ (correct link to my profile)

**Comment by iHiD** [comment]
Fixed on master. Will be deployed today. Thanks for reporting.
