### ISSUE TITLE
reactions: I can react on my own solutions and then can't take it back

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#78]
I wanted to try it out… Now I have a reaction which I can't take back, I can only change it…

**Comment by iHiD** [comment]
Do you not love your own solution? ;)

**Comment by iHiD** [comment]
I "genius" all of mine ;)

**Comment by NobbZ** [comment]
From my experience its very uncommon to be able to "vote" for its own stuff.

Also I do not like beeing unable to revert an accidental click, since I can't take back a reaction to foreign solutions as well.

Especially when beeing on a laptop, false clicks happen easily when moving the mouse around via touchpad.

**Comment by iHiD** [comment]
Done. Thanks.
