### ISSUE TITLE
Unlocked extra exercises modal tweak

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/v2-feedback#79]
The exercise description length should be restricted in this modal. I suggest a maximum of 3 lines. 

<img width="495" alt="screen shot 2017-08-24 at 13 37 30" src="https://user-images.githubusercontent.com/5421823/29666803-c0c2c6c2-88d1-11e7-952c-12a739b9cb04.png">

**Comment by iHiD** [comment]
Triaged. Closing this. Thanks.
