### ISSUE TITLE
Difficulty filter for Extra Exercises is broken

### ISSUE THREAD

**Issue by jonmcalder** [exercism/v2-feedback#8]
Difficulty filter for Extra Exercises on the bottom of track pages seems to be broken/buggy.

Filtering by difficulty either doesn't work at all or yields incorrect results e.g. Easy -> Nothing, Medium & Hard -> Easy

**Comment by kytrinyx** [comment]
Thanks for the heads up, @jonmcalder!

**Comment by ErikSchierboom** [comment]
I have encountered the same issue.

**Comment by kytrinyx** [comment]
Note: this is similar to #25 which talks about the topics filter rather than the difficulty filter.

**Comment by iHiD** [comment]
This should now be fixed. Thanks for reporting.
