### ISSUE TITLE
[Latest Solution]: display has two horizontal scrolls...

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-feedback#80]
relates to #73 

This is what I am seeing:

![scroller](https://user-images.githubusercontent.com/6978003/29667805-ccdcdaf4-88ab-11e7-85f8-229ac8c5b5ff.gif)

Notice the that outer most horizontal scroller changes location as I scroll the browser window vertically.  I am working with Chrome on Windows.  There probably doesn't need to be two horizontal scrollbars.

**Comment by iHiD** [comment]
Triaged to exercism/reboot#139

**Comment by iHiD** [comment]
This is fixed on master now, so I'm going to close it here. It will show up in the next beta (mid-June). Please let me know if you have any further scrolling issues then. Thanks! :)

**Comment by iHiD** [comment]
For reference this is what it looks like now on my mac and what it should look like everywhere: http://recordit.co/5DNrBjbAzj
