### ISSUE TITLE
Blocking Google fonts pushes Genius! button to next row

### ISSUE THREAD

**Issue by katrinleinweber** [exercism/v2-feedback#82]
![screen shot 2017-08-26 at 07 58 35](https://user-images.githubusercontent.com/9948149/29739038-71c4bfbc-8a34-11e7-8f16-7a0348e03490.png)

Seen in Firefox 55.0.2 (64-bit) with uBlock Origin 1.13.8 on MacOS 10.12.6 (16G29). Allowing `fonts.googleapis.com` fixes this. I wonder whether a few more pixels of space there in the `div.react` would also fix this for users who do want to continue blocking 3rd-party scripts?

**Comment by kytrinyx** [comment]
Fonts! There's just no end to how complicated they are.

Thanks @katrinleinweber

**Comment by iHiD** [comment]
I'll look at this and see if there's a simple fix. As a rule though, I don't think we should made modifications for the website for custom scripts that people have running.

**Comment by NobbZ** [comment]
I do not think that it is related to the google-fonts but something else… I do see it exactly as on the screenshot for my own solutions, while other solutions are fine, independently of blokcing or loading those webfonts…

**Comment by iHiD** [comment]
I've fixed this on a branch that will get merged onto master and deployed later today. Thanks for reporting.

**Comment by katrinleinweber** [comment]
You're welcome :-) Thanks for implementing a fix!

> […] As a rule though, I don't think we should made modifications for the website for custom scripts that people have running.

Well, how common is ad- and 3rd-party script blocking? One could say, it is an internet "custom" nowadays ;-) Then again, blocking the Google Fonts may be uncommon, but it is not a personal Greasemonkey script.

I for one hope such issues are rare enough that no general rule will be needed, but a quick discussion can resolve or reject them.
