### ISSUE TITLE
Unnecessary scrollbars displayed on when macOS has "Show scroll bars: Always" setting

### ISSUE THREAD

**Issue by look** [exercism/v2-feedback#85]
I have my Mac configured to "Show scroll bars: Always" (Settings > General) and it causes scroll bars to appear in text inputs even when they would not be necessary. (This will also happen if the user has a mouse plugged in.)

<img width="538" alt="screen shot 2017-08-27 at 11 43 31 am" src="https://user-images.githubusercontent.com/10186/29753006-7f724c1c-8b1d-11e7-95f4-d2207ed69f80.png"> 

Sorry if this is worded strangely since it sounds like I'm complaining about something I've intentionally turned on, but the UI does look incorrect. I believe this can be fixed by setting `overflow: auto` on your editor. See screenshot:

<img width="537" alt="screen shot 2017-08-27 at 11 46 26 am" src="https://user-images.githubusercontent.com/10186/29753008-849c9b5c-8b1d-11e7-934e-9bf4549797af.png">

**Comment by iHiD** [comment]
Triaged to exercism/reboot#140

**Comment by iHiD** [comment]
@look I've fixed this on master. It'll be deployed in the next beta. Thank you! If you spot anything else similar, please let me know :)
