### ISSUE TITLE
Database reset #1

### ISSUE THREAD

**Issue by iHiD** [exercism/v2-feedback#86]
We are about to reset the database and migration over the data from v1. 

- The v2 site will be down for the duration of this (we expect it to last about 5mins). 
- When you log back in, you will be effectively logging into your v1 account with the data as it was.
- We will probably redo this a couple more times over the next couple of weeks.

Please let us know any bugs that you see with your data occurring from this migration. 

Thank you! 💙

**Comment by look** [comment]
Exciting!

I see the tracks I belong to on the Exercism v1, but when I click on one, I get an error screen:

<img width="541" alt="screen shot 2017-08-27 at 4 08 08 pm" src="https://user-images.githubusercontent.com/10186/29754826-269c2bba-8b42-11e7-90cd-bec44f64cd74.png">


(Also, the text should read "_something's_ not working here". The apostrophe is missing.)

**Comment by iHiD** [comment]
@look Congratulations on being the first person to have attempted to see a page with a deprecated exercises on v2 :) Fixed now :)

The (appalling!) typo is fixed too. Thanks for catching that :)

**Comment by look** [comment]
Haha, happy to help. ;)

Another problem: I think I got into a bad state because I still have `nextercism` configured with my old token, but the settings page (https://v2.exercism.io/my/settings) is giving me an error so I can't re-configure it. 

The behavior I'm seeing from the CLI is that I attempt to download an exercise, and an empty line is printed, but nothing is downloaded:

```
adjacent:ruby look$ nextercism download binary-search-tree --track=ruby

```

Here's what `nextercism troubleshoot` prints out:

```
Debug Information
=================

Version
----------------
Current: 3.0.0-alpha.3
Latest:  2.4.1


Operating System
----------------
OS:           darwin
Architecture: amd64


Configuration
----------------
Home:      /Users/look
Workspace: /Users/look/nexercism
Config:    /Users/look/.config/exercism/user.json
API key:   077c*****************************1f5

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 108.936356ms

Exercism:
    * http://exercism.io/api/v1
    * [connected]
    * 183.654792ms

X-API:
    * http://x.exercism.io
    * [connected]
    * 229.831549ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
```

**Comment by iHiD** [comment]
@look Super helpful. Thanks. Caused by us forgetting to generate new auth tokens for everyone. That should be fixed now and added to ETL part 2 for the next db reset.
