### ISSUE TITLE
Mentor opt-out?

### ISSUE THREAD

**Issue by Insti** [exercism/v2-feedback#88]
I have submitted solutions for various tracks, and am listed as a mentor for all of them.
Is there a way for me to turn this off for tracks I feel unqualified for, so they don't clog up my mentor queue?

**Comment by NobbZ** [comment]
I think that would help a lot... But that would be opportune to how v2 shall be after release. Mentorship shall become opt-in.

**Comment by kytrinyx** [comment]
Yes, mentorship is going to be opt-in only, and on a per-track basis. We are doing the first round of v2-feedback with mentorship automatically turned on everywhere for everyone. We will likely turn this off in a second round so that we can test out all the paths to signing up as a mentor, etc.

**Comment by iHiD** [comment]
Triaged the "stop mentoring" feature to exercism/reboot/134
