### ISSUE TITLE
Mentor queue is never-ending

### ISSUE THREAD

**Issue by Insti** [exercism/v2-feedback#89]
It would be nice if the mentor queue only gave you N problems to do, so you could get some feeling of completion by doing 1 "page" worth.

As it is they just keep coming.

There could also be a 'give me more' button to refill the queue.

It would be good if N was configurable so you could set it to a sustainable daily rate.

I'm not sure where the bugs stop and feature requests start :)

**Comment by NobbZ** [comment]
Even worse… There are submissions in my mentoring queue that are 3 years and older… I can't even scroll towards newer. If we have to work through such a backlocg, there will be no progress for a long time…

**Comment by Insti** [comment]
Another Mentor workflow issue:

I like to do a whole batch of the same problem at a time, so I can be sure to be familiar with the problem I'm mentoring and encounter the various ways of solving it.

The v2 mixed queue makes this really hard to do.

**Comment by NobbZ** [comment]
Oh... The stream is mixed by problem as well? I'm just seeing Hamming, but mixed by language. But yes, all those contextswitches break the flow...

**Comment by kytrinyx** [comment]
This is all great feedback, thank you.

> There are submissions in my mentoring queue that are 3 years and older… 

This is a bug in the data migration that I'm looking into.

**Comment by kytrinyx** [comment]
> I like to do a whole batch of the same problem at a time, so I can be sure to be familiar with the problem I'm mentoring and encounter the various ways of solving it.

@Insti this is how I work too. I didn't notice that we hadn't taken this into account until I saw the mentor dashboard with real data. (I'm so glad we're doing this beta testing so we can catch these things!)

**Comment by iHiD** [comment]
Triaged to exercism/reboot#138

**Comment by NobbZ** [comment]
Has the ETL stuff been repaired? Can we have another reset please? All those old stuff in my list and the fact that there are only a handfull of testers, really make the prototype unusable in my eyes…

**Comment by iHiD** [comment]
Yeah. It's unusable atm. It's served its purpose for now to get everyone's
thoughts. We need to iterate all the feedback and then release a new cut.
This is going to take at least a month from now so I doubt there will be
much public movement before then. Agree @kytrinyx?

**Comment by kytrinyx** [comment]
Yeah—I think I fixed the ETL things.

While there's still a bunch of stuff we know needs fixed on the site, I would be happy to do an export, if @iHiD can perform the reset, as this might help make the site usable for other exploration.

**Comment by NobbZ** [comment]
Any progress on this?

Will there be a new reset soon?

**Comment by iHiD** [comment]
@kytrinyx, @nicolechalmers and I are meeting next week to plan things out, so we'll update you then :)

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
