### ISSUE TITLE
Visitor / Contributors missing after database reset

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-feedback#90]
Related to #86

Since 1st database reset the counter at the bottom of the v2 site indicates that there are zero volunteers and no contributors are displayed when any associated links are clicked.

**Comment by iHiD** [comment]
Thanks @rpottsoh. @kytrinyx is turning the existing script into a Github App, at which point this syncing will occur properly. I'll assign this to her and @ccare who will put that in production.

**Comment by iHiD** [comment]
Triaged to https://github.com/exercism/reboot/issues/60

**Comment by iHiD** [comment]
Retriaged to https://github.com/exercism/reboot/issues/171

**Comment by kytrinyx** [comment]
This has been addedto the deploy checklist for the data migration. I'm going to close this.

**Comment by kytrinyx** [comment]
Quick update on this one :)

We did a clean import of recent data, got to the end and discovered that we had changed something which broke the contributor import. So. That's now fixed, and I'm waiting for the folks in the UK to be awake again so they can run the contributor script in production.

**Comment by iHiD** [comment]
I'm awake!! :)
