### ISSUE TITLE
Progressbar hides label

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#91]
The progressbar does hide the actual label with the progress in textual form:

<details>

![label-behind-bar](https://user-images.githubusercontent.com/58951/29793130-08312994-8c43-11e7-831c-5413da872d37.png)
</details>

**Comment by kytrinyx** [comment]
Thanks @NobbZ—that should hopefully be a quick fix.

**Comment by iHiD** [comment]
Fixed locally. Thanks!
