### ISSUE TITLE
When the tracks title is too long you see no progress on its card

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#92]
Title says it all, but I show you an example

![no-progress-long-title](https://user-images.githubusercontent.com/58951/29793229-6baa000e-8c43-11e7-9de3-b80f91129abd.png)

**Comment by kytrinyx** [comment]
Since this is the only track with a long name, so I'm tempted to just rename the track. The website is http://lfe.io so that seems like it would be fine. Then if we make the blurb start with "Lisp Flavoured Erlang..." then people might not be so confused about it.

**Comment by iHiD** [comment]
This is a deliberate design decision in order to keep the cards consistent in terms of height/spacing. 

@kytrinyx Triaged to exercism/reboot#132 for rename the track if you want to.

**Comment by kytrinyx** [comment]
I've opened an issue: https://github.com/exercism/lfe/pull/64

**Comment by iHiD** [comment]
LFE is renamed so this should no longer be an issue in the next ETL.
