### ISSUE TITLE
CTRL+Enter for submitting comment

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#94]
Just hitting CTRL and Enter in conjunction is a way to submit comments that I'm used to from many forums, github and even exercism V1 ;) It would be nice to have it back in V2.

**Comment by kytrinyx** [comment]
Yes, I'd love to have full-on keyboard-only support with shortcuts for everything! Super nice power-user feature.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
