### ISSUE TITLE
Show my/commenters solution

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#95]
When mentoring I'd like to quickjump to my own solution (if applicable) as I am able to with the big `</>` Button in the upper right corner of V1.

Also I really liked to be able to quickjump to a commenters solution when browsing other people submissions as it was possible via the `</>` button below ones comment.

Of course the student shouldn't be able to just peak into the mentors solution ;)

**Comment by Insti** [comment]
> Of course the student shouldn't be able to just peak into the mentors solution 

Why not?

**Comment by NobbZ** [comment]
Because some of them would simply copy paste without even trying to understand. Then it will be hard for a mentor to continue teaching or to see if the student understood or just copied…

Therefore I think its important that only the mentor(s) decide how much code they show to the student.

**Comment by Insti** [comment]
> Because some of them would simply copy paste without even trying to understand. Then it will be hard for a mentor to continue teaching or to see if the student understood or just copied…

There's a lot of ways a student can "cheat", I'd rather trust the students to be honest about their attempts, if they just want to copy/paste without learning they're only cheating themselves.

There's a lot to be learned from viewing other peoples solutions to a problem even if you are still in the process of solving it.

I don't think hiding solutions from students is a good idea.

**Comment by iHiD** [comment]
Student's can view community solutions after they have uploaded their first attempt to a solution. There's not a search facility here (atm at least) so they couldn't specifically find their mentors' attempts to directly "cheat" from them, but can read others' attempts at the same exercise.

> When mentoring I'd like to quickjump to my own solution (if applicable) as I am able to with the big </> Button in the upper right corner of V1.

I'll add to this to our TODO list. Good idea :)

**Comment by iHiD** [comment]
Triaged to exercism/reboot#137

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
