### ISSUE TITLE
There is a blinking cursor on the profile when choosing languages…

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#96]
…that does imply the possibility to type and filter the list (which I really like to do, since my list is long…) but you can't filter or type

![blinking-cursor-suggests-editability](https://user-images.githubusercontent.com/58951/29794426-37835118-8c48-11e7-95c6-639ba0427d9e.png)

**Comment by iHiD** [comment]
Can you type/filter on the topic selector at the top of the side exercises of https://v2.exercism.io/my/tracks/ruby (or equiv track)?

**Comment by NobbZ** [comment]
Yes I am able to, and I am able to do so as well on the profile now. Not sure what happened earlier… Perhaps I#ve confused the script by hitting `CTRL-A`, `Backspace` to delete the content first?

**Comment by NobbZ** [comment]
No, it was because I tried to type directly after clicking it, but I have to delete the current content first by hitting Backspace, without typing something else first… Perhaps delete on first keypress?

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
