### ISSUE TITLE
Solutions you've liked page doesn't show track nor exercise

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#98]
On the Solutions you've liked page, I can see an overview of which solutions I've liked. However, I can't see the solution's exercise name nor the solution's track, both of which are important pieces of information.

**Comment by kytrinyx** [comment]
Ah, yes—that would be quite important to have :) Thank you!

**Comment by iHiD** [comment]
Triaged to exercism/reboot#135

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
