### ISSUE TITLE
Add filtering to Solutions you've liked page

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#99]
It would be convenient to be able to filter the Solutions you've liked page, to help find that one like you are looking for. Possible filters would be: track, exercise, submitter, status (well done, love, genius).

**Comment by kytrinyx** [comment]
Agreed, this would be handy. Thanks!

**Comment by iHiD** [comment]
Triaged to exercism/reboot#135

**Comment by samir-majhi** [comment]
Merging https://github.com/exercism/discussions/issues/198 into this one.

**Comment by kytrinyx** [comment]
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._
